#include <stdio.h>
#include <stdint.h>
int main() {
printf("%d\n", 53);;
printf("%d\n", 17);;
int32_t a = 33 + (18 + 46);
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", 62);;
printf("%d\n", (a + 31) * a);;
printf("%d\n", (a + 10) * a);;
int32_t b = a;
printf("%d\n", 48);;
printf("%d\n", 7);;
printf("%d\n", b);;
printf("%d\n", b);;
printf("%d\n", 15);;
printf("%d\n", 34);;
printf("%d\n", b * 21);;
printf("%d\n", 78 * 59);;
printf("%d\n", 29 * 4);;
printf("%d\n", a * (a - 16));;
int32_t c = a;
printf("%d\n", c);;
printf("%d\n", 31 + (b / b));;
printf("%d\n", c - 47);;
printf("%d\n", 36 - 29);;
int32_t d = 18;
printf("%d\n", d / 16);;
int32_t e = (16 + a) + b;
printf("%d\n", e);;
printf("%d\n", (e - 3) + (22 / e));;
printf("%d\n", c);;
int32_t f = d;
int32_t g = 73;
printf("%d\n", d - g);;
int32_t h = 2 - 21;
printf("%d\n", a * ((56 + 10) - ((41 * g) + 5)));;
printf("%d\n", c);;
printf("%d\n", 40 - 13);;
printf("%d\n", 23 * 3);;
printf("%d\n", 23);;
printf("%d\n", 7);;
printf("%d\n", e);;
printf("%d\n", 62);;
printf("%d\n", f);;
printf("%d\n", 36);;
int32_t i = 14;
printf("%d\n", 31);;
printf("%d\n", 117 * h);;
printf("%d\n", 67);;
printf("%d\n", b);;
int32_t j = h;
int32_t k = 12;
printf("%d\n", e / c);;
printf("%d\n", 29);;
printf("%d\n", j);;
printf("%d\n", 6 + c);;
printf("%d\n", (b / 21) * c);;
printf("%d\n", 7);;
printf("%d\n", 16);;
printf("%d\n", e);;
int32_t l = 20;
printf("%d\n", k);;
int32_t m = h;
int32_t n = 19;
int32_t o = n;
printf("%d\n", m);;
int32_t p = l;
printf("%d\n", m);;
printf("%d\n", 51);;
printf("%d\n", d);;
printf("%d\n", 7);;
printf("%d\n", j);;
int32_t q = 24;
printf("%d\n", p);;
printf("%d\n", 6);;
printf("%d\n", b);;
int32_t r = 10;
printf("%d\n", 1);;
int32_t s = 53 / i;
printf("%d\n", f - (i / 17));;
printf("%d\n", 20);;
printf("%d\n", 89);;
printf("%d\n", 56);;
int32_t t = a;
printf("%d\n", i);;
printf("%d\n", 27);;
printf("%d\n", 22);;
printf("%d\n", k);;
printf("%d\n", (o + k) - 7);;
printf("%d\n", 35);;
printf("%d\n", 78);;
int32_t u = 59;
int32_t v = t;
printf("%d\n", 28);;
printf("%d\n", ((4 * 7) + 31) * (64 - c));;
printf("%d\n", d);;
printf("%d\n", 37 / q);;
printf("%d\n", 4 * v);;
int32_t w = q;
printf("%d\n", 26);;
int32_t x = p - b;
printf("%d\n", 19);;
printf("%d\n", 24 / (68 * (l - 5)));;
printf("%d\n", p);;
printf("%d\n", c);;
printf("%d\n", c + 25);;
printf("%d\n", 16);;
int32_t y = d;
printf("%d\n", 2);;
int32_t z = b - (p / 73);
printf("%d\n", 0);;
int32_t aa = (6 + k) + 28;
printf("%d\n", h + e);;
printf("%d\n", h);;
printf("%d\n", r);;
printf("%d\n", h);;
printf("%d\n", r + 9);;
int32_t ab = a;
int32_t ac = 62;
printf("%d\n", o);;
printf("%d\n", z);;
int32_t ad = ((b * (k + i)) / b) - ((ab + 36) * (9 + ac));
int32_t ae = 79;
printf("%d\n", ab + (k - (f / t)));;
printf("%d\n", 52);;
printf("%d\n", 50);;
printf("%d\n", ((62 - ((19 / b) * 24)) / 53) / 19);;
printf("%d\n", d);;
printf("%d\n", (16 / 47) / 9);;
printf("%d\n", t);;
printf("%d\n", i);;
printf("%d\n", 64);;
printf("%d\n", ((6 / (aa * 31)) + ae) * (46 - (35 - (((95 * ((78 - 39) * ((ab * (j * aa)) + 23))) * (53 * i)) + d))));;
printf("%d\n", v / b);;
int32_t af = 8;
printf("%d\n", m);;
printf("%d\n", r / 83);;
printf("%d\n", n);;
printf("%d\n", s);;
printf("%d\n", ad / (6 - (((o - 8) + s) / p)));;
int32_t ag = (6 + ac) * ((22 / 32) + 1);
int32_t ah = h;
printf("%d\n", f);;
int32_t ai = r;
printf("%d\n", t);;
printf("%d\n", 49);;
printf("%d\n", 12 - r);;
printf("%d\n", 16);;
int32_t aj = 16;
int32_t ak = r;
printf("%d\n", ad);;
printf("%d\n", af - g);;
printf("%d\n", k);;
int32_t al = 36;
printf("%d\n", 28);;
int32_t am = af;
printf("%d\n", 36);;
printf("%d\n", w);;
printf("%d\n", (af * aj) / ad);;
printf("%d\n", r / ak);;
printf("%d\n", y);;
int32_t an = j;
int32_t ao = 19 / (s + ae);
printf("%d\n", 17);;
printf("%d\n", 17);;
int32_t ap = v;
int32_t aq = 4;
printf("%d\n", (32 / v) / 22);;
printf("%d\n", n / (29 - z));;
printf("%d\n", 62 - 69);;
printf("%d\n", (((((75 + 18) - am) + ((j + i) + (((ad * ag) + n) + (29 - (al + 2))))) + ao) + ad) * 53);;
printf("%d\n", ab);;
printf("%d\n", a);;
printf("%d\n", i);;
printf("%d\n", ac);;
printf("%d\n", 47);;
printf("%d\n", 35);;
printf("%d\n", 43 + q);;
printf("%d\n", y + e);;
printf("%d\n", 86);;
printf("%d\n", 25);;
printf("%d\n", 8 + 3);;
printf("%d\n", 23);;
printf("%d\n", ((7 - 16) / aj) + ((p - 5) / k));;
return 0;}