#include <stdio.h>
#include <stdint.h>
int main() {
printf("%d\n", 19);;
int32_t a = 18 - (23 + ((97 * 18) + 48));
printf("%d\n", ((1 - (0 * (((a * ((34 - 30) + (((15 / 20) * (93 + 27)) - 62))) + ((((a - a) / (a / 60)) / 29) / a)) / 1))) / 35) - (a / a));;
int32_t b = a;
printf("%d\n", 59);;
printf("%d\n", b / (((40 + (b / 70)) + 19) - b));;
printf("%d\n", a);;
int32_t c = a;
printf("%d\n", 12);;
printf("%d\n", 54);;
printf("%d\n", a);;
printf("%d\n", b - 70);;
printf("%d\n", 24);;
printf("%d\n", c);;
int32_t d = (68 / 50) * 14;
int32_t e = d - ((26 / 3) + d);
printf("%d\n", 38);;
printf("%d\n", d);;
int32_t f = e;
printf("%d\n", a * 3);;
int32_t g = d;
int32_t h = 41;
printf("%d\n", 17);;
printf("%d\n", 15);;
printf("%d\n", b);;
printf("%d\n", 9 + 11);;
printf("%d\n", h);;
printf("%d\n", (((27 / 28) - 21) - ((d - (28 - 29)) / 19)) * 15);;
int32_t i = (72 / 8) - (b / (((2 * a) * b) / 58));
printf("%d\n", a);;
printf("%d\n", 20);;
printf("%d\n", g / 28);;
int32_t j = (42 / (63 / e)) / (19 * h);
printf("%d\n", 28);;
printf("%d\n", h);;
printf("%d\n", c);;
int32_t k = j;
printf("%d\n", 19);;
printf("%d\n", 3 + j);;
printf("%d\n", g);;
printf("%d\n", 47);;
int32_t l = 62 / 11;
printf("%d\n", b);;
printf("%d\n", 12);;
printf("%d\n", d - 27);;
printf("%d\n", k - (k * 40));;
int32_t m = 70;
printf("%d\n", h);;
printf("%d\n", d / e);;
printf("%d\n", g);;
printf("%d\n", 39);;
printf("%d\n", 64);;
printf("%d\n", c);;
printf("%d\n", 73);;
printf("%d\n", 16 / l);;
int32_t n = 73;
printf("%d\n", d);;
int32_t o = d;
printf("%d\n", 25);;
printf("%d\n", f);;
int32_t p = c;
printf("%d\n", 30 * b);;
printf("%d\n", 53 * p);;
printf("%d\n", k + 10);;
printf("%d\n", j);;
printf("%d\n", a);;
printf("%d\n", f - 39);;
printf("%d\n", d);;
printf("%d\n", a);;
printf("%d\n", 31);;
printf("%d\n", (73 + (k + (((48 * b) + (h * (69 / (d + 71)))) * i))) + (16 + ((d * (13 + 4)) + h)));;
printf("%d\n", ((k / (k + 21)) - 9) - (a / n));;
int32_t q = (n + 99) - 22;
printf("%d\n", 27 / 18);;
printf("%d\n", 10 - n);;
printf("%d\n", ((10 - 30) * (a + h)) / 3);;
printf("%d\n", 38);;
printf("%d\n", 15);;
printf("%d\n", 19 * (16 + o));;
printf("%d\n", n);;
printf("%d\n", d / b);;
printf("%d\n", b / 20);;
printf("%d\n", 54);;
int32_t r = c;
printf("%d\n", 55);;
printf("%d\n", 73);;
printf("%d\n", 6);;
printf("%d\n", q);;
printf("%d\n", k);;
printf("%d\n", 29);;
int32_t s = 9 / 6;
printf("%d\n", 2);;
int32_t t = g - ((i * s) * ((((s / ((j - s) - 21)) - 67) * h) / g));
int32_t u = 13;
printf("%d\n", a);;
printf("%d\n", 36);;
printf("%d\n", h / (49 * 57));;
printf("%d\n", 72 + n);;
printf("%d\n", (e * a) * r);;
int32_t v = (c - ((((s - (68 + t)) - d) * p) * n)) - 67;
printf("%d\n", m);;
int32_t w = p;
int32_t x = (s + 26) * s;
printf("%d\n", j + l);;
printf("%d\n", 43);;
printf("%d\n", 53);;
int32_t y = 9;
printf("%d\n", 2 * (j - 20));;
printf("%d\n", (a * 34) * ((90 / 23) + (a * (3 * n))));;
int32_t z = t + v;
printf("%d\n", 58);;
int32_t aa = 39;
printf("%d\n", z / p);;
int32_t ab = 39 * 22;
int32_t ac = s + (q / 3);
printf("%d\n", 19);;
int32_t ad = 3 / 39;
printf("%d\n", t);;
printf("%d\n", l * 49);;
printf("%d\n", 9 * m);;
printf("%d\n", 19);;
printf("%d\n", ad);;
int32_t ae = 37 * l;
printf("%d\n", ad);;
return 0;}