#include <stdio.h>
#include <stdint.h>
int main() {
printf("%d\n", 37 * (((((((14 * 73) + 15) + (1 - 15)) + 19) + ((67 * (45 / 31)) * (((((2 * 12) + (71 / 1)) - 11) - (42 * 34)) + 23))) - 24) * ((26 * 54) + 1)));;
int32_t a = 70 * ((1 - (25 / 57)) + (10 * (((59 - 7) * 12) * (29 - 59))));
printf("%d\n", 13);;
int32_t b = a;
int32_t c = b;
printf("%d\n", c);;
int32_t d = b * (b * c);
printf("%d\n", b);;
int32_t e = 9;
printf("%d\n", b);;
printf("%d\n", 44 - d);;
printf("%d\n", 0);;
printf("%d\n", 50);;
int32_t f = c;
printf("%d\n", 19);;
printf("%d\n", c);;
printf("%d\n", 14);;
int32_t g = 29;
printf("%d\n", g);;
printf("%d\n", 23);;
printf("%d\n", 17);;
int32_t h = 17;
int32_t i = a;
int32_t j = e;
printf("%d\n", 60);;
printf("%d\n", a + c);;
printf("%d\n", 4);;
printf("%d\n", 84);;
int32_t k = e;
printf("%d\n", f);;
printf("%d\n", f * (10 + 28));;
int32_t l = 13;
printf("%d\n", g);;
int32_t m = e;
printf("%d\n", f * (i - 28));;
printf("%d\n", g);;
printf("%d\n", h);;
int32_t n = 39 * (95 + k);
printf("%d\n", 15);;
int32_t o = k;
printf("%d\n", (11 - (((h - 33) + (6 / 1)) * k)) + 9);;
printf("%d\n", g);;
printf("%d\n", m);;
printf("%d\n", 4);;
int32_t p = i * f;
printf("%d\n", n);;
int32_t q = i / e;
printf("%d\n", i);;
printf("%d\n", 7);;
printf("%d\n", (14 / 50) * m);;
int32_t r = h;
printf("%d\n", 58);;
int32_t s = c;
printf("%d\n", o / r);;
int32_t t = m;
printf("%d\n", p);;
printf("%d\n", 12 - 49);;
printf("%d\n", i);;
printf("%d\n", q * (i - ((((4 / 52) - 76) + 22) / p)));;
printf("%d\n", b);;
printf("%d\n", 73 / (((35 / c) / (s - (q / (i * f)))) - ((((9 - 58) + b) / s) - (n * ((o - (15 / 75)) / 54)))));;
printf("%d\n", 71);;
printf("%d\n", 46);;
printf("%d\n", 22);;
printf("%d\n", 4);;
printf("%d\n", f);;
int32_t u = 18 - m;
printf("%d\n", g);;
printf("%d\n", d);;
printf("%d\n", r);;
printf("%d\n", (d * (30 / ((((((15 + d) - 4) * 29) + ((d * 2) - (((17 / (u * (i + i))) + 7) + 61))) - 30) * (t * g)))) - (((57 * (40 * a)) - ((48 / k) / 28)) + j));;
printf("%d\n", 71);;
printf("%d\n", 46 - k);;
int32_t v = 45;
printf("%d\n", 31);;
int32_t w = (((30 - k) - (35 - 9)) / ((0 + (n - (27 / 9))) - ((e - (((f - 11) + 23) / l)) - (q * (8 - 36))))) - d;
int32_t x = 44 + (72 / o);
int32_t y = 34;
printf("%d\n", 38);;
printf("%d\n", f - 54);;
int32_t z = n;
printf("%d\n", 3 + ((v / 58) - 29));;
printf("%d\n", 6);;
printf("%d\n", 54);;
printf("%d\n", d);;
printf("%d\n", n);;
int32_t aa = 55;
printf("%d\n", 20);;
printf("%d\n", o / 64);;
printf("%d\n", (o * ((d * (((q * a) * (36 - b)) / (s * (((106 - 27) / s) + (42 / 6))))) * (28 / t))) * ((u - a) - (e / 74)));;
int32_t ab = o;
printf("%d\n", v);;
printf("%d\n", 40 / (108 * r));;
printf("%d\n", (e * y) / 26);;
printf("%d\n", 45 / aa);;
printf("%d\n", g);;
printf("%d\n", g + h);;
int32_t ac = r * e;
printf("%d\n", t);;
int32_t ad = 34;
printf("%d\n", e * (((52 * 16) - g) / u));;
printf("%d\n", l);;
printf("%d\n", c);;
printf("%d\n", (g * m) * ((81 + a) * g));;
printf("%d\n", l);;
printf("%d\n", w);;
printf("%d\n", 55);;
printf("%d\n", x);;
printf("%d\n", 86);;
printf("%d\n", p);;
printf("%d\n", 16);;
printf("%d\n", g);;
printf("%d\n", 4);;
printf("%d\n", 28 - 31);;
printf("%d\n", 36);;
int32_t ae = 2;
printf("%d\n", n);;
int32_t af = (e - ((z * f) * (p / (46 + ((((23 / m) / 40) + (o * ((ae + 14) * 10))) + x))))) - i;
printf("%d\n", 65 * c);;
printf("%d\n", 54);;
printf("%d\n", 12 * y);;
printf("%d\n", 70);;
int32_t ag = 20 - (16 + (9 - ((21 + k) + a)));
printf("%d\n", ab);;
int32_t ah = 71 + af;
printf("%d\n", 6);;
printf("%d\n", u);;
int32_t ai = 34;
printf("%d\n", 26);;
printf("%d\n", p);;
printf("%d\n", 17);;
printf("%d\n", (24 * 22) - n);;
printf("%d\n", j);;
printf("%d\n", 31 * 30);;
printf("%d\n", ac);;
printf("%d\n", 57);;
printf("%d\n", o);;
printf("%d\n", 61);;
printf("%d\n", 28 / 12);;
printf("%d\n", ac);;
printf("%d\n", ac);;
printf("%d\n", 83 * (((ab * h) / (((34 + g) / 32) * p)) - (((o / 12) - z) + (b + (24 * ((ai + 66) * ((30 * 40) * ((p / 50) - 73))))))));;
printf("%d\n", 34 * 41);;
int32_t aj = g;
printf("%d\n", 62);;
printf("%d\n", ((d - (47 * (19 - 44))) - (u * 18)) / 28);;
printf("%d\n", 10);;
printf("%d\n", 65);;
int32_t ak = ab * 12;
printf("%d\n", ab * ah);;
printf("%d\n", v);;
printf("%d\n", w - 87);;
int32_t al = (aa + 9) + ((19 / ac) - z);
printf("%d\n", ad);;
printf("%d\n", aj);;
printf("%d\n", (125 - aj) - (v - ae));;
int32_t am = 14;
printf("%d\n", ae);;
printf("%d\n", 23);;
printf("%d\n", 28 / 49);;
printf("%d\n", 73 + ((e - ab) - (44 / ((ae - (48 * 21)) + ac))));;
printf("%d\n", f);;
printf("%d\n", (r / (((f / z) - ((ai + (13 / 10)) * ((ac - r) * aa))) * (((al * aa) - 12) - y))) - m);;
int32_t an = (26 / b) - ak;
printf("%d\n", 25 * o);;
printf("%d\n", 101);;
printf("%d\n", 27);;
printf("%d\n", al + (65 + 25));;
printf("%d\n", 45);;
printf("%d\n", af);;
printf("%d\n", (18 * (14 + ((41 / e) * 33))) + (31 * 83));;
printf("%d\n", 68);;
printf("%d\n", w);;
printf("%d\n", 50 / 12);;
printf("%d\n", 2 * 4);;
int32_t ao = ag + 46;
printf("%d\n", 90);;
printf("%d\n", ((al + u) / (e / (t - (u / 3)))) - 2);;
int32_t ap = al;
printf("%d\n", 24);;
int32_t aq = 28;
printf("%d\n", (((89 * 39) / (78 / (67 / ae))) * w) * r);;
int32_t ar = 52;
int32_t as = (4 / ((13 * w) * d)) - ((((81 + ab) * 27) / (37 + 4)) / 42);
printf("%d\n", (4 + 17) + ((53 * (48 - (ae * 65))) / as));;
int32_t at = i + y;
printf("%d\n", 31);;
printf("%d\n", ak);;
printf("%d\n", 33);;
printf("%d\n", 9);;
printf("%d\n", 13);;
printf("%d\n", ar);;
printf("%d\n", 25);;
printf("%d\n", ai);;
int32_t au = u;
printf("%d\n", (af * v) / 59);;
int32_t av = o;
int32_t aw = (z + ((45 - g) * 27)) * i;
int32_t ax = 59;
printf("%d\n", 68 / x);;
printf("%d\n", 9);;
printf("%d\n", ag);;
int32_t ay = 14;
printf("%d\n", ab);;
printf("%d\n", au * (39 * o));;
int32_t az = ad;
printf("%d\n", m);;
int32_t bb = ap;
printf("%d\n", p * s);;
printf("%d\n", am);;
printf("%d\n", ae);;
printf("%d\n", 33);;
printf("%d\n", i);;
printf("%d\n", 12 * 45);;
printf("%d\n", ak);;
printf("%d\n", ac + 35);;
printf("%d\n", aa);;
printf("%d\n", 31);;
printf("%d\n", (37 * (28 * (((((12 - ((63 / 5) - ((bb / (h - 8)) * 25))) - aw) * aw) + af) + 91))) - 45);;
printf("%d\n", aj / ag);;
printf("%d\n", j);;
printf("%d\n", ak);;
printf("%d\n", au);;
printf("%d\n", 21);;
printf("%d\n", r);;
printf("%d\n", ab / 16);;
printf("%d\n", ak);;
printf("%d\n", 33);;
int32_t bc = 27;
printf("%d\n", 51);;
printf("%d\n", 58);;
printf("%d\n", r);;
printf("%d\n", 35);;
int32_t bd = 40;
int32_t be = t / (g + c);
printf("%d\n", ((4 - 38) + (13 + ((43 + am) + an))) * bd);;
printf("%d\n", 39 - 56);;
int32_t bf = ae;
printf("%d\n", v * ((10 - 18) / (aa / 16)));;
printf("%d\n", at);;
int32_t bg = 97;
printf("%d\n", (al * (21 + ag)) - (w * (69 - t)));;
printf("%d\n", ad);;
printf("%d\n", at);;
printf("%d\n", y);;
printf("%d\n", 25);;
printf("%d\n", 1 * (47 * ae));;
printf("%d\n", ((17 / az) * 19) / (n / 52));;
printf("%d\n", 80 - at);;
printf("%d\n", 41);;
return 0;}