#include <stdio.h>
#include <stdint.h>
int main() {
printf("%d\n", 5);;
printf("%d\n", 16);;
int32_t a = ((58 * 39) + (14 + (40 * 89))) - 9;
printf("%d\n", a);;
printf("%d\n", 38);;
printf("%d\n", a);;
printf("%d\n", 4);;
int32_t b = a + 4;
int32_t c = 4;
printf("%d\n", 26 + c);;
printf("%d\n", a - 2);;
printf("%d\n", (a / (c * c)) - 16);;
printf("%d\n", b + ((a - 43) - (24 / 10)));;
printf("%d\n", 22);;
printf("%d\n", c);;
printf("%d\n", 59);;
printf("%d\n", 106 * c);;
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", 46);;
printf("%d\n", c);;
printf("%d\n", 41);;
printf("%d\n", b);;
printf("%d\n", 59);;
int32_t d = 41 * 29;
printf("%d\n", 32);;
int32_t e = c;
printf("%d\n", b);;
printf("%d\n", 6);;
printf("%d\n", c);;
int32_t f = e;
printf("%d\n", 3);;
printf("%d\n", d);;
printf("%d\n", c * (79 - b));;
printf("%d\n", 58 * (d * 52));;
printf("%d\n", 83 + 20);;
printf("%d\n", f);;
printf("%d\n", (100 - a) * 12);;
printf("%d\n", d);;
printf("%d\n", 41);;
printf("%d\n", c * 9);;
printf("%d\n", 18 - (65 - 57));;
printf("%d\n", c);;
int32_t g = 39;
int32_t h = 39;
printf("%d\n", b);;
int32_t i = 60 / (5 * c);
printf("%d\n", f);;
printf("%d\n", (13 - d) - 19);;
printf("%d\n", 55 * (((2 / (i - c)) + (a / f)) + h));;
printf("%d\n", 8);;
printf("%d\n", a / a);;
printf("%d\n", 8);;
printf("%d\n", (34 + ((51 * b) - c)) - ((14 / 22) - 54));;
printf("%d\n", 21);;
int32_t j = 93;
printf("%d\n", 80 + 2);;
printf("%d\n", a);;
printf("%d\n", 12 - 29);;
printf("%d\n", g * ((c / 25) * (b - e)));;
int32_t k = h / (i + (28 + (19 * 7)));
printf("%d\n", d);;
printf("%d\n", b);;
int32_t l = 14;
printf("%d\n", 43);;
printf("%d\n", 66);;
printf("%d\n", h);;
printf("%d\n", 15);;
printf("%d\n", 1);;
printf("%d\n", 74);;
printf("%d\n", h);;
printf("%d\n", d);;
printf("%d\n", 62 * g);;
int32_t m = ((3 * (c * (55 + (((c + i) * (8 + 1)) * (((87 * 1) + 51) - (11 - 25)))))) / 42) - (30 * 10);
printf("%d\n", e);;
int32_t n = 17 - 19;
printf("%d\n", 62);;
printf("%d\n", a);;
printf("%d\n", d);;
printf("%d\n", 8);;
printf("%d\n", (65 * g) / 67);;
int32_t o = m;
printf("%d\n", 73);;
printf("%d\n", d);;
printf("%d\n", n);;
printf("%d\n", (l + (i / c)) + 29);;
printf("%d\n", (13 + c) / 11);;
printf("%d\n", ((((a / 37) / d) * c) / 1) + (g * n));;
printf("%d\n", 17);;
printf("%d\n", 39);;
int32_t p = a;
printf("%d\n", g);;
int32_t q = 35;
printf("%d\n", 13);;
printf("%d\n", (((o / (18 * (50 / 41))) / 58) - ((i / b) + (a + 14))) - (m / j));;
int32_t r = n + 69;
int32_t s = 67 * g;
printf("%d\n", c);;
printf("%d\n", 9 - 92);;
printf("%d\n", j);;
int32_t t = l;
int32_t u = (s + 27) * e;
printf("%d\n", 10);;
printf("%d\n", n);;
int32_t v = f;
printf("%d\n", (e + e) / 46);;
printf("%d\n", 16 / d);;
int32_t w = 38;
printf("%d\n", 10);;
printf("%d\n", (((39 - 2) * 40) / p) + 57);;
printf("%d\n", 14);;
printf("%d\n", 48 / ((4 * (((g - ((((34 - 4) - h) / p) / ((i + 9) + 78))) + 91) + d)) + r));;
printf("%d\n", 50 - (g - (a / ((l + b) + (t * 12)))));;
int32_t x = e + c;
int32_t y = ((((61 * u) + x) * g) - (12 / j)) - w;
printf("%d\n", 49);;
printf("%d\n", 38);;
printf("%d\n", v);;
printf("%d\n", ((h - 49) / (32 / x)) / ((5 * v) / 10));;
printf("%d\n", 45);;
int32_t z = i;
printf("%d\n", 11);;
printf("%d\n", c);;
int32_t aa = (v - z) / ((j - ((7 - 6) + 70)) - 3);
printf("%d\n", f);;
printf("%d\n", 81 - 2);;
int32_t ab = p;
int32_t ac = 18;
printf("%d\n", 36);;
int32_t ad = v;
printf("%d\n", 52);;
int32_t ae = i;
printf("%d\n", h);;
int32_t af = 38 + ab;
int32_t ag = 19;
printf("%d\n", (12 + 27) * 4);;
int32_t ah = (c - u) / 22;
int32_t ai = 48;
printf("%d\n", z);;
printf("%d\n", j);;
int32_t aj = s;
printf("%d\n", 14);;
printf("%d\n", 19 * af);;
int32_t ak = l;
printf("%d\n", (d / (v * (q * g))) - (v + ak));;
printf("%d\n", 42);;
printf("%d\n", 84);;
printf("%d\n", 41 + (w / l));;
printf("%d\n", 40);;
printf("%d\n", ac);;
printf("%d\n", w - aa);;
printf("%d\n", y);;
printf("%d\n", 15);;
printf("%d\n", s);;
printf("%d\n", p);;
printf("%d\n", s);;
printf("%d\n", (aa * ah) + ((ad + ((o - u) + r)) - (b / 26)));;
printf("%d\n", z / 9);;
printf("%d\n", 3 / 12);;
int32_t al = h + x;
int32_t am = (4 + 79) - 60;
printf("%d\n", (q * am) - d);;
printf("%d\n", ((45 - (15 + (b / 34))) * al) - 32);;
printf("%d\n", (28 / ak) - (33 / 8));;
int32_t an = 42;
int32_t ao = (ab * 11) * ak;
return 0;}