#include <stdio.h>
#include <stdint.h>
int main() {
printf("%d\n", 8);;
int32_t a = 24;
int32_t b = a * 28;
printf("%d\n", 5);;
int32_t c = a;
printf("%d\n", b);;
printf("%d\n", 73);;
printf("%d\n", 60);;
printf("%d\n", a);;
printf("%d\n", c);;
printf("%d\n", a / (2 * c));;
int32_t d = a + c;
printf("%d\n", d);;
printf("%d\n", a);;
printf("%d\n", (b + 6) / 23);;
printf("%d\n", c / d);;
printf("%d\n", 10);;
printf("%d\n", a);;
printf("%d\n", 15 * a);;
printf("%d\n", d);;
printf("%d\n", 93);;
printf("%d\n", 15);;
printf("%d\n", b);;
printf("%d\n", d);;
int32_t e = b;
int32_t f = e;
printf("%d\n", 50 - d);;
int32_t g = c;
printf("%d\n", (20 + 32) / (f / 5));;
printf("%d\n", e);;
int32_t h = 28;
printf("%d\n", f);;
printf("%d\n", h);;
printf("%d\n", a);;
int32_t i = (e + 13) + d;
printf("%d\n", e);;
printf("%d\n", h);;
printf("%d\n", 20);;
printf("%d\n", f);;
printf("%d\n", 56);;
printf("%d\n", 25);;
printf("%d\n", 30 + h);;
printf("%d\n", i);;
printf("%d\n", 1);;
printf("%d\n", g);;
printf("%d\n", d / ((16 / 52) + e));;
printf("%d\n", ((((((50 / 35) + (e - e)) * 20) + e) / 62) - h) * f);;
printf("%d\n", b / e);;
printf("%d\n", b);;
printf("%d\n", 21);;
printf("%d\n", 28);;
int32_t j = 24;
printf("%d\n", 113);;
printf("%d\n", 6);;
int32_t k = b;
printf("%d\n", k);;
printf("%d\n", b);;
int32_t l = 7;
int32_t m = 0;
printf("%d\n", 46 / ((a * h) - c));;
printf("%d\n", 10 * f);;
printf("%d\n", k);;
printf("%d\n", k / k);;
printf("%d\n", 16);;
int32_t n = 18 - (64 / d);
printf("%d\n", a);;
printf("%d\n", i);;
printf("%d\n", (m + (f * (f - (44 + (38 + 32))))) / n);;
printf("%d\n", n);;
printf("%d\n", g * 74);;
printf("%d\n", n);;
printf("%d\n", 57);;
printf("%d\n", d / g);;
printf("%d\n", 37);;
int32_t o = k;
printf("%d\n", d - 22);;
printf("%d\n", i - b);;
printf("%d\n", c);;
printf("%d\n", (h + 24) + 51);;
printf("%d\n", 33 * n);;
printf("%d\n", 25 * a);;
printf("%d\n", b + 31);;
printf("%d\n", n + 64);;
printf("%d\n", e);;
printf("%d\n", 8);;
int32_t p = 8;
printf("%d\n", 8);;
int32_t q = n;
printf("%d\n", o);;
int32_t r = d;
int32_t s = 18;
printf("%d\n", h + (23 + a));;
int32_t t = q;
int32_t u = 28;
printf("%d\n", (50 / (18 * k)) * (s / 11));;
printf("%d\n", 3);;
printf("%d\n", e);;
printf("%d\n", 94);;
printf("%d\n", k);;
int32_t v = ((b + ((i - (58 / r)) + 13)) * (t / (31 / 1))) * 11;
printf("%d\n", v);;
int32_t w = t;
int32_t x = (b / i) / (h * ((83 * (((m * c) + (q * 13)) / (13 - p))) - a));
printf("%d\n", b + 54);;
printf("%d\n", 74);;
printf("%d\n", (e + m) + 52);;
printf("%d\n", r);;
int32_t y = 15;
int32_t z = (((44 - (a * 51)) * 7) * b) - 32;
int32_t aa = w;
int32_t ab = 5;
int32_t ac = o;
printf("%d\n", p);;
printf("%d\n", 35 + (123 / p));;
printf("%d\n", (61 - w) + 23);;
printf("%d\n", 14);;
printf("%d\n", 91 * 24);;
printf("%d\n", j);;
printf("%d\n", 11);;
printf("%d\n", s + 0);;
printf("%d\n", m);;
int32_t ad = u - 54;
int32_t ae = r;
printf("%d\n", 22 * ab);;
int32_t af = x + ((b - 23) / 39);
printf("%d\n", 41);;
int32_t ag = 99;
int32_t ah = ae / ae;
int32_t ai = b;
printf("%d\n", a * (r - (45 + r)));;
int32_t aj = l;
int32_t ak = 86;
printf("%d\n", 35);;
int32_t al = 21;
int32_t am = (af + o) - aj;
printf("%d\n", f);;
printf("%d\n", x);;
printf("%d\n", ad);;
printf("%d\n", 11);;
printf("%d\n", n - 36);;
printf("%d\n", 22);;
int32_t an = 20 * 11;
printf("%d\n", q);;
printf("%d\n", x - f);;
printf("%d\n", 61);;
printf("%d\n", ah);;
int32_t ao = n;
printf("%d\n", aa);;
int32_t ap = c;
printf("%d\n", j / (s - (ai + i)));;
printf("%d\n", x);;
int32_t aq = z;
printf("%d\n", ab - 52);;
printf("%d\n", 19 / n);;
int32_t ar = t;
printf("%d\n", aj);;
printf("%d\n", u);;
printf("%d\n", b);;
printf("%d\n", (aj + (aj + af)) / ((46 + (an - 9)) / ah));;
printf("%d\n", 74);;
printf("%d\n", 27);;
int32_t as = 11 + (((25 - b) * 34) * (61 - ((ak + (4 + 9)) - 7)));
printf("%d\n", t);;
printf("%d\n", 12);;
printf("%d\n", 41 * q);;
printf("%d\n", ao);;
printf("%d\n", 1);;
printf("%d\n", x);;
int32_t at = 15 - k;
printf("%d\n", aq);;
int32_t au = 82 + as;
printf("%d\n", ((4 + (k * s)) + ((ae / ae) / (18 - (18 * c)))) * 12);;
int32_t av = r;
printf("%d\n", t * j);;
printf("%d\n", af);;
int32_t aw = n;
printf("%d\n", 14);;
int32_t ax = a;
printf("%d\n", u);;
int32_t ay = 8;
printf("%d\n", 30);;
printf("%d\n", 25);;
int32_t az = ag;
printf("%d\n", 47);;
int32_t bb = 35;
printf("%d\n", h + (k * 4));;
printf("%d\n", ay * au);;
printf("%d\n", ((m / 52) - 9) * i);;
printf("%d\n", av);;
printf("%d\n", u);;
printf("%d\n", 44 + 22);;
printf("%d\n", 44);;
printf("%d\n", ar / (8 - l));;
printf("%d\n", (43 + 14) - p);;
int32_t bc = (e / an) * 92;
printf("%d\n", ao);;
printf("%d\n", (f + 25) * 26);;
printf("%d\n", c);;
printf("%d\n", f - (23 * 26));;
printf("%d\n", as);;
int32_t bd = 14;
int32_t be = 7;
printf("%d\n", 19 / ay);;
printf("%d\n", 41);;
int32_t bf = s + (25 + ((t / (91 * 7)) * (25 + ((ao * (47 * (aa + (23 * n)))) - ((57 * e) / as)))));
printf("%d\n", ao);;
printf("%d\n", 8);;
printf("%d\n", ah * al);;
printf("%d\n", ((ag - (h + (at + (66 * ((v + aw) + 64))))) * (((37 * ar) * 35) * v)) - bd);;
printf("%d\n", 60);;
printf("%d\n", 42);;
printf("%d\n", 52);;
int32_t bg = 1;
printf("%d\n", z);;
int32_t bh = 6 - 10;
printf("%d\n", o);;
int32_t bi = l;
return 0;}