#include <stdio.h>
#include <stdint.h>
int main() {
int32_t a = 32;
printf("%d\n", 26);;
printf("%d\n", (57 * (a + ((27 / 42) - a))) / 67);;
int32_t b = (a * 23) + 30;
printf("%d\n", b);;
printf("%d\n", b);;
printf("%d\n", b);;
printf("%d\n", 44 / a);;
int32_t c = 31;
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", a * ((c * a) / (c * b)));;
printf("%d\n", 22);;
int32_t d = b;
int32_t e = b;
printf("%d\n", 63);;
printf("%d\n", 15);;
printf("%d\n", 42);;
int32_t f = 37 - 5;
printf("%d\n", e);;
printf("%d\n", e);;
printf("%d\n", 9);;
printf("%d\n", f);;
printf("%d\n", 12);;
int32_t g = a;
printf("%d\n", (32 + a) + 9);;
printf("%d\n", f);;
printf("%d\n", 16);;
printf("%d\n", 2 + 1);;
int32_t h = 15;
printf("%d\n", e + h);;
int32_t i = 40;
printf("%d\n", c * i);;
printf("%d\n", f - 42);;
printf("%d\n", 63);;
printf("%d\n", 31);;
printf("%d\n", f);;
int32_t j = d * 2;
printf("%d\n", 24);;
printf("%d\n", (92 + (c - (i * 22))) + ((1 + c) / 67));;
printf("%d\n", j / a);;
printf("%d\n", 12);;
printf("%d\n", ((44 / 27) - (a - 27)) / f);;
printf("%d\n", 33);;
printf("%d\n", 37);;
printf("%d\n", (33 - e) - c);;
int32_t k = e;
printf("%d\n", h);;
int32_t l = k;
int32_t m = 21;
printf("%d\n", k);;
int32_t n = (e * ((((115 / 7) * 46) - ((40 / 17) / d)) - (94 * c))) / f;
printf("%d\n", h);;
int32_t o = g * 29;
int32_t p = h + 10;
printf("%d\n", (7 - n) + (10 / 28));;
printf("%d\n", h);;
printf("%d\n", f / (37 / 19));;
printf("%d\n", a + 37);;
printf("%d\n", o);;
printf("%d\n", g);;
printf("%d\n", 3);;
printf("%d\n", p);;
printf("%d\n", d);;
printf("%d\n", h);;
printf("%d\n", a * (17 + (60 + 34)));;
printf("%d\n", c);;
printf("%d\n", (k * ((66 * 13) + (26 + h))) / n);;
printf("%d\n", e - a);;
int32_t q = 3;
printf("%d\n", ((46 - 31) - g) + ((o / (k + 28)) + b));;
printf("%d\n", b);;
printf("%d\n", f - 10);;
int32_t r = 10;
printf("%d\n", g * 55);;
printf("%d\n", 57 + d);;
printf("%d\n", 12 * ((o * 47) / 19));;
printf("%d\n", 19 - r);;
int32_t s = 28 - o;
printf("%d\n", 19);;
printf("%d\n", 20);;
printf("%d\n", p);;
printf("%d\n", 29);;
int32_t t = 2 * (((34 * p) / r) - j);
printf("%d\n", l);;
printf("%d\n", 16 * m);;
printf("%d\n", h * (85 - p));;
printf("%d\n", l);;
printf("%d\n", q);;
printf("%d\n", 19);;
printf("%d\n", e);;
printf("%d\n", 64);;
int32_t u = n;
printf("%d\n", a);;
printf("%d\n", 20);;
printf("%d\n", 43);;
printf("%d\n", t - 18);;
int32_t v = 1 + a;
int32_t w = a;
printf("%d\n", 11);;
printf("%d\n", w * m);;
printf("%d\n", 15);;
printf("%d\n", (v / 35) + 28);;
printf("%d\n", 7 + k);;
int32_t x = 7;
printf("%d\n", 51);;
printf("%d\n", 63);;
printf("%d\n", 36);;
printf("%d\n", 71);;
printf("%d\n", d / 3);;
int32_t y = j + 13;
printf("%d\n", 28);;
printf("%d\n", ((19 * y) + (16 * l)) / g);;
printf("%d\n", t);;
printf("%d\n", w);;
printf("%d\n", y);;
printf("%d\n", s);;
printf("%d\n", j);;
printf("%d\n", q);;
int32_t z = e;
printf("%d\n", r);;
int32_t aa = (c * ((22 * (5 + w)) + l)) - (19 / (s / 33));
printf("%d\n", (q * (41 - (8 - o))) + ((3 - 49) + 21));;
printf("%d\n", 5);;
printf("%d\n", 0 + 23);;
printf("%d\n", n);;
int32_t ab = ((s + r) + ((((45 - 12) * a) - 33) / 7)) + f;
printf("%d\n", (m + 16) / 1);;
printf("%d\n", ((15 + d) / 70) + 55);;
printf("%d\n", w);;
printf("%d\n", 16);;
printf("%d\n", 3 + z);;
printf("%d\n", 61);;
int32_t ac = l;
int32_t ad = 9;
printf("%d\n", 4);;
printf("%d\n", 24);;
printf("%d\n", b);;
int32_t ae = 36;
int32_t af = (c + 45) / 107;
printf("%d\n", ac);;
int32_t ag = e;
printf("%d\n", 5);;
printf("%d\n", j * 55);;
printf("%d\n", af);;
printf("%d\n", ag);;
printf("%d\n", aa);;
int32_t ah = m;
printf("%d\n", ab);;
int32_t ai = 22;
int32_t aj = (5 + v) / (47 + ((51 + (af + (y - (24 - (14 + (43 * y)))))) - n));
printf("%d\n", t);;
int32_t ak = 46;
int32_t al = 2;
printf("%d\n", af - (s + 31));;
printf("%d\n", 56);;
printf("%d\n", 1);;
printf("%d\n", ((43 + t) - (49 / (24 - ak))) - y);;
printf("%d\n", ah);;
int32_t am = 3;
printf("%d\n", 31 + ai);;
printf("%d\n", 8);;
printf("%d\n", 7);;
int32_t an = u;
int32_t ao = 93 - ae;
printf("%d\n", ad);;
int32_t ap = 35;
int32_t aq = s;
printf("%d\n", 23);;
printf("%d\n", af * b);;
printf("%d\n", p - 76);;
printf("%d\n", 40);;
printf("%d\n", g);;
printf("%d\n", c);;
printf("%d\n", ah);;
printf("%d\n", ab);;
printf("%d\n", ao);;
printf("%d\n", ah);;
printf("%d\n", ((23 * 42) * ((d / g) + 37)) - t);;
printf("%d\n", 7);;
int32_t ar = an;
printf("%d\n", 11 * k);;
int32_t as = ac + ad;
printf("%d\n", 4);;
int32_t at = aq;
printf("%d\n", (i - ab) + (86 - 40));;
printf("%d\n", 40);;
printf("%d\n", 51 + (aj / ad));;
printf("%d\n", 17);;
int32_t au = ak - ((z * 55) / 62);
printf("%d\n", 26);;
printf("%d\n", ah);;
printf("%d\n", ad + 68);;
printf("%d\n", 46);;
int32_t av = c;
printf("%d\n", 9 + (av + 64));;
printf("%d\n", 28 + 49);;
int32_t aw = 21 * b;
int32_t ax = aq;
printf("%d\n", 7);;
int32_t ay = (ak + (u * n)) + 22;
printf("%d\n", am);;
printf("%d\n", z + ((6 * 21) * (36 + u)));;
int32_t az = 24;
int32_t bb = 32;
printf("%d\n", 32);;
printf("%d\n", 21 / (ax / (32 / 28)));;
printf("%d\n", (f + g) * ag);;
printf("%d\n", 10);;
printf("%d\n", 51);;
printf("%d\n", i);;
printf("%d\n", 15);;
printf("%d\n", 68);;
printf("%d\n", 47);;
int32_t bc = ac + 50;
printf("%d\n", aq);;
printf("%d\n", ay + ac);;
int32_t bd = 24;
printf("%d\n", 39);;
int32_t be = u;
int32_t bf = g - 101;
printf("%d\n", aq);;
printf("%d\n", 25);;
printf("%d\n", 48);;
printf("%d\n", 56);;
int32_t bg = 14;
int32_t bh = ak - ((ay + d) + ao);
printf("%d\n", 5);;
printf("%d\n", y + 58);;
printf("%d\n", 20 / (bb * 72));;
printf("%d\n", 44);;
printf("%d\n", bf);;
printf("%d\n", 46);;
printf("%d\n", 13);;
printf("%d\n", ar);;
printf("%d\n", 6);;
int32_t bi = g;
int32_t bj = ((v + p) + 7) / 19;
printf("%d\n", al);;
printf("%d\n", 76 * 15);;
int32_t bk = (((am + 13) + (e - (((aq / (j * (u - ae))) / (((34 - ((5 + 71) * 35)) * 68) / 21)) / (27 - (bd + 31))))) - 62) * g;
int32_t bl = 46;
printf("%d\n", 36);;
int32_t bm = 4;
printf("%d\n", ai);;
printf("%d\n", (30 / u) * t);;
printf("%d\n", z);;
printf("%d\n", 56);;
printf("%d\n", s);;
printf("%d\n", m);;
int32_t bn = 29 + 77;
return 0;}