#include <stdio.h>
#include <stdint.h>
int main() {
int32_t a = 45;
printf("%d\n", (2 - a) / ((a - a) + (a * 10)));;
printf("%d\n", 29);;
printf("%d\n", 30);;
printf("%d\n", 64 / a);;
printf("%d\n", 24);;
printf("%d\n", a);;
printf("%d\n", a);;
int32_t b = a;
printf("%d\n", 13);;
printf("%d\n", 19 * b);;
printf("%d\n", a);;
printf("%d\n", 10);;
int32_t c = 50;
printf("%d\n", c);;
int32_t d = a - 25;
printf("%d\n", a / 35);;
printf("%d\n", c);;
printf("%d\n", 2);;
int32_t e = 11;
printf("%d\n", (b + (((b * (68 + 24)) - d) / c)) + c);;
printf("%d\n", d);;
printf("%d\n", a * 21);;
int32_t f = 55;
printf("%d\n", ((25 - c) * 6) / b);;
int32_t g = b;
printf("%d\n", (g + 19) - e);;
int32_t h = 30;
printf("%d\n", c - ((d * (e / c)) / 47));;
int32_t i = b;
int32_t j = ((48 * (d - 22)) - (17 * h)) * (94 / (19 + h));
printf("%d\n", i - (((a + ((2 - j) + (h / (((72 - i) - e) / 6)))) + (32 * 29)) + (((d / e) * 46) / 63)));;
printf("%d\n", i);;
printf("%d\n", a);;
printf("%d\n", h);;
int32_t k = 13;
printf("%d\n", c);;
int32_t l = 16;
printf("%d\n", (46 + a) / (1 * 13));;
printf("%d\n", (27 - 96) - 71);;
printf("%d\n", f);;
printf("%d\n", l);;
printf("%d\n", g);;
int32_t m = a;
printf("%d\n", k);;
printf("%d\n", 2);;
printf("%d\n", ((l + 25) / m) + h);;
printf("%d\n", 73);;
int32_t n = f;
printf("%d\n", 44);;
int32_t o = 14;
printf("%d\n", 12);;
int32_t p = a;
printf("%d\n", 11);;
printf("%d\n", 65);;
printf("%d\n", 64);;
printf("%d\n", e * 34);;
printf("%d\n", 15);;
int32_t q = p;
int32_t r = 9;
int32_t s = (((38 + 2) * (((56 + 21) * d) / (h * (48 - a)))) - (58 * (m + 106))) + 31;
printf("%d\n", i);;
printf("%d\n", 11);;
printf("%d\n", o);;
printf("%d\n", (p - i) / 39);;
printf("%d\n", 26 - 12);;
int32_t t = 21;
int32_t u = 16;
printf("%d\n", 50);;
printf("%d\n", 6);;
printf("%d\n", 18);;
printf("%d\n", 33);;
int32_t v = t;
printf("%d\n", t);;
printf("%d\n", n - q);;
printf("%d\n", t);;
int32_t w = 3 / (59 + i);
printf("%d\n", j);;
int32_t x = 15 + (e + 9);
printf("%d\n", (((47 - 25) + 64) * (((13 + k) - t) / f)) - f);;
printf("%d\n", n + 54);;
int32_t y = b;
int32_t z = 31 + l;
int32_t aa = a;
int32_t ab = 72 - g;
printf("%d\n", u);;
printf("%d\n", 31);;
printf("%d\n", 34);;
printf("%d\n", t - q);;
printf("%d\n", (20 / (9 + 36)) / (25 - (54 + 17)));;
printf("%d\n", (b * 31) + 2);;
int32_t ac = x;
printf("%d\n", 8);;
printf("%d\n", p);;
return 0;}