#include <stdio.h>
#include <stdint.h>
int main() {
printf("%d\n", 0 / 34);;
int32_t a = 2;
printf("%d\n", a);;
printf("%d\n", (23 - ((a - a) / 25)) + 57);;
printf("%d\n", 33);;
int32_t b = (a + a) * ((62 / a) - 60);
printf("%d\n", b);;
printf("%d\n", 50);;
int32_t c = 33;
printf("%d\n", c);;
printf("%d\n", 16);;
int32_t d = a + (((34 / c) - ((22 / a) * (18 + b))) / c);
printf("%d\n", 18);;
printf("%d\n", c);;
printf("%d\n", a);;
printf("%d\n", c);;
printf("%d\n", (c - c) - 30);;
int32_t e = ((((38 * b) + c) * ((9 - 20) + c)) - 42) * 30;
printf("%d\n", 30);;
printf("%d\n", d);;
printf("%d\n", 14 / (13 - 11));;
printf("%d\n", 2);;
int32_t f = b;
printf("%d\n", ((81 / 23) - 24) * 79);;
int32_t g = b;
printf("%d\n", 54);;
printf("%d\n", a);;
printf("%d\n", 23 / (c + e));;
printf("%d\n", a * e);;
printf("%d\n", 13);;
printf("%d\n", 43);;
printf("%d\n", c);;
printf("%d\n", f);;
int32_t h = f;
int32_t i = 21;
printf("%d\n", 30 * ((b + ((39 + 3) - i)) * d));;
printf("%d\n", 76 * 7);;
printf("%d\n", 2);;
printf("%d\n", 9);;
printf("%d\n", 21);;
printf("%d\n", f);;
printf("%d\n", d);;
printf("%d\n", 20);;
printf("%d\n", 15);;
printf("%d\n", (i * h) / (g * 17));;
int32_t j = g;
printf("%d\n", 46);;
printf("%d\n", (41 - 50) + g);;
printf("%d\n", (34 / (f + (d + (i * i)))) - e);;
int32_t k = 19;
printf("%d\n", c);;
printf("%d\n", (32 / 103) * ((j + 41) + (b - b)));;
printf("%d\n", a);;
printf("%d\n", f);;
printf("%d\n", 25);;
int32_t l = b;
printf("%d\n", k / 27);;
int32_t m = 2;
printf("%d\n", 40);;
printf("%d\n", 8);;
printf("%d\n", 3);;
printf("%d\n", 18);;
printf("%d\n", 31);;
int32_t n = m;
int32_t o = 9;
printf("%d\n", k);;
printf("%d\n", h);;
int32_t p = ((f * 90) + (27 + 26)) + a;
printf("%d\n", 58 / 19);;
printf("%d\n", n);;
printf("%d\n", h + ((o - g) + (((11 / (((o * (h + (((f - 17) + (24 + l)) * 50))) / (53 - 51)) - 51)) * (((81 + (n / j)) * (2 - j)) / 6)) - ((29 / 15) / 19))));;
printf("%d\n", k);;
printf("%d\n", l + 9);;
int32_t q = 23;
int32_t r = 19;
printf("%d\n", p);;
int32_t s = 52 / n;
printf("%d\n", 30);;
int32_t t = 100;
printf("%d\n", l);;
printf("%d\n", q - (38 + 19));;
int32_t u = 46;
printf("%d\n", 43 - f);;
int32_t v = k * 39;
printf("%d\n", p / 2);;
printf("%d\n", 23 * 17);;
int32_t w = v / i;
int32_t x = 1 - d;
printf("%d\n", t + w);;
printf("%d\n", d);;
printf("%d\n", i * t);;
printf("%d\n", 56 * 54);;
printf("%d\n", g);;
printf("%d\n", 8);;
printf("%d\n", l);;
printf("%d\n", (v / (j + 96)) - 23);;
printf("%d\n", 88 + (e + 1));;
printf("%d\n", r * h);;
printf("%d\n", 47);;
int32_t y = 24;
printf("%d\n", (y - 13) + j);;
printf("%d\n", 8 - (((66 + j) / k) / 33));;
int32_t z = 4;
printf("%d\n", ((l + 27) + (o * a)) - q);;
printf("%d\n", 91);;
printf("%d\n", (2 - a) + a);;
printf("%d\n", v / w);;
printf("%d\n", w);;
int32_t aa = (30 / 115) / 36;
printf("%d\n", a);;
printf("%d\n", u);;
int32_t ab = m;
int32_t ac = (12 - 5) / (8 / ((56 + d) / c));
printf("%d\n", (((c * ab) - h) / i) / ((((25 * c) - r) - aa) * v));;
printf("%d\n", 3 - 64);;
int32_t ad = j - ((f / 22) / s);
printf("%d\n", 7);;
printf("%d\n", 22 / 9);;
printf("%d\n", (((y + d) * h) * (((26 + ab) / ((q - (f / l)) + y)) + 71)) + (59 / v));;
printf("%d\n", d);;
printf("%d\n", 36);;
printf("%d\n", (i - 61) * 26);;
printf("%d\n", 56 - (18 + ((y - v) * s)));;
printf("%d\n", i);;
printf("%d\n", 32);;
printf("%d\n", 6);;
printf("%d\n", 2 + e);;
int32_t ae = 36;
printf("%d\n", 15);;
printf("%d\n", m);;
int32_t af = v;
int32_t ag = 39;
printf("%d\n", u);;
int32_t ah = 35 - l;
printf("%d\n", 26);;
printf("%d\n", 12);;
printf("%d\n", l - 27);;
int32_t ai = q;
int32_t aj = z / 30;
printf("%d\n", w / (36 * ((((55 * (l * 15)) + ah) + n) + 36)));;
printf("%d\n", g);;
int32_t ak = 51 / (2 - 63);
printf("%d\n", 40);;
printf("%d\n", i);;
printf("%d\n", 46);;
printf("%d\n", ac);;
printf("%d\n", 21);;
printf("%d\n", o + ((g - ah) / 24));;
printf("%d\n", (46 / (46 / 33)) + 31);;
int32_t al = (42 + ai) - v;
printf("%d\n", 42 * 54);;
printf("%d\n", 44);;
return 0;}