#include <stdio.h>
#include <stdint.h>
int main() {
printf("%d\n", 47);;
int32_t a = ((66 * 9) / 26) + 60;
int32_t b = (a * a) * 96;
int32_t c = a + a;
printf("%d\n", a);;
printf("%d\n", 42);;
printf("%d\n", (20 / (43 * b)) + (c - 12));;
printf("%d\n", 96 / c);;
printf("%d\n", 40);;
printf("%d\n", b);;
printf("%d\n", (b - b) - 6);;
printf("%d\n", 32);;
int32_t d = 1;
printf("%d\n", c * b);;
printf("%d\n", 30);;
printf("%d\n", 12);;
int32_t e = 73;
printf("%d\n", 14);;
int32_t f = 48;
printf("%d\n", 7);;
int32_t g = b;
printf("%d\n", f);;
printf("%d\n", 37);;
printf("%d\n", 31 * b);;
printf("%d\n", (47 / e) - a);;
int32_t h = f;
int32_t i = h;
printf("%d\n", 29 + i);;
printf("%d\n", (f + 6) - e);;
printf("%d\n", b);;
printf("%d\n", 60);;
printf("%d\n", a);;
printf("%d\n", 9 / (52 + (b - 2)));;
printf("%d\n", 8 + e);;
printf("%d\n", 21);;
int32_t j = 15;
printf("%d\n", h);;
int32_t k = c;
printf("%d\n", a);;
int32_t l = g * j;
printf("%d\n", k);;
printf("%d\n", 16);;
printf("%d\n", (l * 58) * 15);;
printf("%d\n", 21 * h);;
printf("%d\n", 18);;
printf("%d\n", i / (l * l));;
printf("%d\n", e);;
printf("%d\n", b);;
int32_t m = h;
int32_t n = d;
int32_t o = a;
printf("%d\n", 52);;
int32_t p = a;
printf("%d\n", (39 - f) + f);;
int32_t q = g;
printf("%d\n", p * 2);;
printf("%d\n", j);;
printf("%d\n", 27 * (a + ((m / (44 + o)) * e)));;
int32_t r = (40 + ((89 + (q + 42)) - 38)) / c;
printf("%d\n", 12 / 59);;
printf("%d\n", 27);;
printf("%d\n", g);;
printf("%d\n", o);;
printf("%d\n", f);;
printf("%d\n", (q / l) / (42 + 60));;
printf("%d\n", q);;
printf("%d\n", j);;
printf("%d\n", 11);;
printf("%d\n", m);;
printf("%d\n", 49);;
int32_t s = n;
printf("%d\n", 13);;
printf("%d\n", 48 * ((q * (((k - (b - (1 - f))) / 25) * 11)) + 30));;
printf("%d\n", 5);;
printf("%d\n", 33);;
int32_t t = j;
printf("%d\n", d);;
printf("%d\n", d);;
printf("%d\n", j);;
printf("%d\n", 84);;
printf("%d\n", 2);;
int32_t u = 5;
printf("%d\n", 22);;
printf("%d\n", 97);;
printf("%d\n", (33 / o) + (h + (t * m)));;
printf("%d\n", h);;
printf("%d\n", 29 * 68);;
printf("%d\n", 61 + g);;
printf("%d\n", 15);;
printf("%d\n", 10);;
int32_t v = (f * a) + (g * k);
printf("%d\n", 13);;
printf("%d\n", 49 - n);;
printf("%d\n", k);;
int32_t w = 35;
printf("%d\n", 36);;
printf("%d\n", s);;
printf("%d\n", (52 + n) - m);;
printf("%d\n", p);;
printf("%d\n", 35);;
int32_t x = 18;
printf("%d\n", p + s);;
printf("%d\n", 20);;
printf("%d\n", 19);;
printf("%d\n", b);;
printf("%d\n", 79);;
printf("%d\n", 85);;
printf("%d\n", k - v);;
printf("%d\n", (35 * q) / 7);;
int32_t y = 57;
int32_t z = 40;
printf("%d\n", 18);;
printf("%d\n", 56);;
int32_t aa = e;
printf("%d\n", 30 + i);;
printf("%d\n", 24);;
printf("%d\n", z);;
printf("%d\n", 21);;
printf("%d\n", v);;
printf("%d\n", 6);;
printf("%d\n", c);;
printf("%d\n", 100);;
printf("%d\n", ((73 + (w * 1)) - ((65 / 4) / 33)) * 3);;
printf("%d\n", 92 + ((aa * 21) / (68 / 23)));;
printf("%d\n", l);;
printf("%d\n", 54);;
printf("%d\n", 28);;
return 0;}