#include <stdio.h>
#include <stdint.h>
int main() {
printf("%d\n", 41);;
printf("%d\n", 26);;
printf("%d\n", 19 + 45);;
int32_t a = 11;
int32_t b = 1;
printf("%d\n", 43 / b);;
int32_t c = b;
int32_t d = 13;
int32_t e = 32 * 31;
int32_t f = 27 * ((a + 5) - e);
printf("%d\n", c);;
printf("%d\n", 7);;
int32_t g = 21;
printf("%d\n", e * 30);;
printf("%d\n", 17);;
int32_t h = 13;
int32_t i = f;
printf("%d\n", e);;
printf("%d\n", g);;
printf("%d\n", 3);;
printf("%d\n", ((((f - h) + g) + i) - (((0 / e) * d) / c)) + g);;
printf("%d\n", e * c);;
printf("%d\n", 13);;
int32_t j = e;
printf("%d\n", d / j);;
printf("%d\n", d * 77);;
printf("%d\n", 7 / (24 + ((28 + ((52 + d) - (5 + i))) * f)));;
int32_t k = i;
printf("%d\n", g - 5);;
int32_t l = 13 * (28 / ((36 + (72 / 81)) * ((18 - i) / h)));
printf("%d\n", g);;
int32_t m = a;
int32_t n = d / a;
int32_t o = g;
int32_t p = 70;
printf("%d\n", 35);;
printf("%d\n", 29);;
int32_t q = 10;
printf("%d\n", h);;
printf("%d\n", 29);;
int32_t r = 27;
printf("%d\n", 13);;
int32_t s = h;
printf("%d\n", 1);;
printf("%d\n", h);;
printf("%d\n", 0);;
printf("%d\n", m);;
printf("%d\n", 17);;
printf("%d\n", 11 / 20);;
printf("%d\n", k);;
printf("%d\n", k);;
int32_t t = g;
printf("%d\n", g);;
printf("%d\n", 53);;
int32_t u = 11;
printf("%d\n", r);;
printf("%d\n", 1);;
int32_t v = 31;
printf("%d\n", 41);;
int32_t w = n;
printf("%d\n", 33);;
int32_t x = 77;
printf("%d\n", d / a);;
int32_t y = e;
return 0;}