#include <stdio.h>
#include <stdint.h>
int main() {
printf("%d\n", 0);;
int32_t a = ((33 - (34 - (20 - (24 / 23)))) - 41) * 1;
printf("%d\n", a - a);;
printf("%d\n", a);;
printf("%d\n", 42 + (5 * (66 + a)));;
printf("%d\n", a);;
int32_t b = 14;
int32_t c = a;
printf("%d\n", b);;
printf("%d\n", 77);;
printf("%d\n", 50);;
printf("%d\n", c);;
printf("%d\n", 6 - c);;
int32_t d = 36;
printf("%d\n", 21);;
printf("%d\n", (((b / (((d - 42) - d) + 62)) * (56 / (((16 - 30) + b) - (57 * 15)))) - b) * (57 + 21));;
printf("%d\n", 29 + d);;
int32_t e = a;
printf("%d\n", (59 * c) / 26);;
printf("%d\n", b);;
printf("%d\n", e);;
printf("%d\n", e - (95 / (((1 + 44) + 6) / (e + b))));;
printf("%d\n", 11 * ((27 + (c / (b * 64))) + 7));;
int32_t f = 43;
printf("%d\n", 15);;
printf("%d\n", f);;
int32_t g = 77;
printf("%d\n", a);;
printf("%d\n", 11);;
printf("%d\n", (f + a) - e);;
printf("%d\n", 50);;
printf("%d\n", 6);;
printf("%d\n", a);;
int32_t h = 22 + d;
printf("%d\n", 43);;
printf("%d\n", 72 * (13 * ((b * 3) * (h * ((2 * 34) - (a * 15))))));;
printf("%d\n", b);;
printf("%d\n", g);;
printf("%d\n", 1);;
printf("%d\n", (61 + d) * d);;
printf("%d\n", (e / 45) / c);;
printf("%d\n", 3);;
int32_t i = 29;
printf("%d\n", ((55 - i) - ((107 / e) - f)) * (g * (11 - c)));;
printf("%d\n", 58);;
int32_t j = 77 + g;
printf("%d\n", j);;
printf("%d\n", e * 10);;
printf("%d\n", d);;
printf("%d\n", 48);;
printf("%d\n", h / g);;
printf("%d\n", i);;
printf("%d\n", a);;
printf("%d\n", 25);;
int32_t k = 60;
printf("%d\n", g * 1);;
int32_t l = (13 + 2) / c;
printf("%d\n", g);;
int32_t m = 2;
printf("%d\n", i);;
printf("%d\n", 55);;
printf("%d\n", e * ((15 - 14) / h));;
printf("%d\n", (f + c) + 65);;
printf("%d\n", 21);;
printf("%d\n", l);;
printf("%d\n", 7);;
printf("%d\n", d);;
int32_t n = 45;
int32_t o = g;
printf("%d\n", 35);;
printf("%d\n", 4 / 49);;
printf("%d\n", c);;
printf("%d\n", 20);;
printf("%d\n", c + l);;
int32_t p = c;
printf("%d\n", 46 * 38);;
return 0;}