#include <stdio.h>
#include <stdint.h>
int main() {
printf("%d\n", 12);;
int32_t a = ((6 * 56) - 33) * ((63 + 11) + 33);
printf("%d\n", a);;
int32_t b = a * 37;
printf("%d\n", (43 - b) + b);;
int32_t c = 8 * b;
printf("%d\n", 65 * b);;
printf("%d\n", 7);;
printf("%d\n", c);;
printf("%d\n", 2 + (113 + c));;
printf("%d\n", (48 / (27 * 3)) * (b / 38));;
printf("%d\n", 15);;
printf("%d\n", 0 - a);;
printf("%d\n", c);;
int32_t d = 29;
printf("%d\n", 18);;
printf("%d\n", c);;
printf("%d\n", 62);;
printf("%d\n", 30);;
printf("%d\n", 50 - 15);;
printf("%d\n", c);;
printf("%d\n", b + 43);;
printf("%d\n", b - a);;
printf("%d\n", 5);;
printf("%d\n", 42);;
printf("%d\n", 39);;
printf("%d\n", 32);;
printf("%d\n", 90);;
printf("%d\n", a);;
int32_t e = a;
int32_t f = 9;
printf("%d\n", a);;
printf("%d\n", d);;
printf("%d\n", f);;
printf("%d\n", 13);;
printf("%d\n", a / ((c + ((15 - (d * 17)) - a)) * b));;
printf("%d\n", 45);;
int32_t g = 21;
printf("%d\n", b - a);;
int32_t h = d;
printf("%d\n", ((((((12 + h) - 46) / e) + h) * (a * (13 + f))) * (e / 29)) / h);;
int32_t i = e;
printf("%d\n", 43);;
printf("%d\n", ((d * 37) / ((((((((((55 - g) - i) / (d - b)) * 66) / 10) + (2 - (27 * d))) * a) + (25 - 59)) - g) + ((i - c) - ((((((e * (10 * 3)) + 7) - g) / ((53 * 27) / 60)) + (13 - 7)) + f)))) * 95);;
int32_t j = 13;
int32_t k = 66;
printf("%d\n", k);;
printf("%d\n", 25);;
printf("%d\n", h);;
printf("%d\n", 80);;
printf("%d\n", 2);;
printf("%d\n", (j + (j / 38)) - ((((35 + (i + 52)) / 17) + ((3 + e) - 6)) + 59));;
printf("%d\n", g);;
int32_t l = g;
printf("%d\n", 34);;
int32_t m = 45;
int32_t n = a;
printf("%d\n", (42 - (k / k)) * 28);;
printf("%d\n", g);;
int32_t o = h;
int32_t p = ((h * k) / c) + 69;
printf("%d\n", 10);;
printf("%d\n", f);;
printf("%d\n", o);;
printf("%d\n", 69 * ((f + (c + 69)) / 3));;
printf("%d\n", l);;
printf("%d\n", o + (g / (22 * 29)));;
printf("%d\n", 47 - ((j + (e * 36)) / o));;
printf("%d\n", 13);;
int32_t q = c - ((6 * 29) * f);
printf("%d\n", i / ((q / a) * ((43 - 52) - ((59 * (35 - (5 * 8))) * i))));;
printf("%d\n", n);;
printf("%d\n", o);;
printf("%d\n", e);;
printf("%d\n", n);;
printf("%d\n", (p - 21) - (j * 72));;
printf("%d\n", b);;
printf("%d\n", 31);;
int32_t r = p;
printf("%d\n", i);;
printf("%d\n", 2);;
int32_t s = c;
printf("%d\n", b);;
printf("%d\n", 30);;
printf("%d\n", k);;
printf("%d\n", q);;
printf("%d\n", ((72 - 46) * (f / d)) * d);;
printf("%d\n", (s / s) / a);;
printf("%d\n", d);;
int32_t t = i;
printf("%d\n", 23);;
printf("%d\n", 4);;
printf("%d\n", 1);;
printf("%d\n", 73);;
int32_t u = 22;
int32_t v = i;
printf("%d\n", e);;
printf("%d\n", s + 43);;
printf("%d\n", 7 * 15);;
printf("%d\n", 67);;
printf("%d\n", p);;
printf("%d\n", g);;
int32_t w = 4;
printf("%d\n", 69);;
return 0;}