#include <stdio.h>
#include <stdint.h>
int main() {
int32_t a = 95;
printf("%d\n", 6);;
printf("%d\n", 25);;
printf("%d\n", a);;
int32_t b = a;
int32_t c = a;
printf("%d\n", b);;
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", 14);;
printf("%d\n", a);;
printf("%d\n", 55);;
int32_t d = 31;
printf("%d\n", c);;
printf("%d\n", ((17 + 96) / d) * 30);;
printf("%d\n", b);;
printf("%d\n", c);;
int32_t e = 34;
printf("%d\n", 33 / 59);;
printf("%d\n", 36);;
printf("%d\n", 1);;
printf("%d\n", 1);;
int32_t f = 32;
printf("%d\n", d * 4);;
int32_t g = a + a;
printf("%d\n", f);;
printf("%d\n", f);;
printf("%d\n", 56 - 2);;
int32_t h = 14;
int32_t i = e;
printf("%d\n", c);;
printf("%d\n", 34);;
printf("%d\n", g);;
printf("%d\n", 33);;
printf("%d\n", 37 + (c * 15));;
printf("%d\n", c);;
printf("%d\n", 43);;
printf("%d\n", d);;
printf("%d\n", ((g + (((41 * g) / (e + (b + (b * 43)))) * h)) / ((4 - e) - h)) / 26);;
printf("%d\n", c);;
printf("%d\n", 38);;
printf("%d\n", e);;
printf("%d\n", c);;
printf("%d\n", b);;
printf("%d\n", 91);;
printf("%d\n", 19);;
printf("%d\n", (d - h) * 33);;
printf("%d\n", 65 / (e - b));;
printf("%d\n", f);;
int32_t j = (d * a) * 64;
printf("%d\n", 17);;
printf("%d\n", g);;
printf("%d\n", 21);;
printf("%d\n", i);;
int32_t k = f;
printf("%d\n", ((d / 25) * ((((43 - 61) + (h / d)) * 68) * (d + j))) + (22 * 29));;
printf("%d\n", 51);;
printf("%d\n", 19 + c);;
printf("%d\n", e);;
printf("%d\n", j);;
printf("%d\n", (f + ((((39 * d) / (h * f)) + 10) - 50)) + (j * h));;
printf("%d\n", 78 + 9);;
printf("%d\n", 2 * 34);;
int32_t l = c;
int32_t m = ((d + ((((h - 22) + f) * l) - (k - 48))) / 3) - l;
printf("%d\n", 59);;
printf("%d\n", 10);;
printf("%d\n", 6);;
int32_t n = k;
int32_t o = (6 - 27) * h;
int32_t p = 6;
int32_t q = 16;
printf("%d\n", 55 / j);;
printf("%d\n", d);;
printf("%d\n", 44);;
int32_t r = 36;
printf("%d\n", g);;
printf("%d\n", n);;
printf("%d\n", 57);;
printf("%d\n", p);;
printf("%d\n", ((b + ((88 + n) / (54 + 40))) / 24) / k);;
printf("%d\n", 39);;
printf("%d\n", p - (i + a));;
printf("%d\n", 20);;
printf("%d\n", (75 + (d + c)) - 34);;
printf("%d\n", 39 + 21);;
printf("%d\n", 3 - (0 + ((((h / f) / (74 + 2)) + d) + 9)));;
printf("%d\n", d);;
int32_t s = f;
int32_t t = m;
printf("%d\n", 7);;
printf("%d\n", 11);;
printf("%d\n", 50);;
printf("%d\n", 19);;
int32_t u = 24;
printf("%d\n", q);;
printf("%d\n", s);;
printf("%d\n", d);;
int32_t v = 35;
printf("%d\n", n);;
printf("%d\n", 1);;
printf("%d\n", t);;
printf("%d\n", 49);;
printf("%d\n", 2);;
int32_t w = b;
printf("%d\n", t);;
int32_t x = k;
printf("%d\n", 10 / 28);;
int32_t y = ((c / k) * k) * (b - 6);
printf("%d\n", i);;
printf("%d\n", h);;
printf("%d\n", 8);;
printf("%d\n", v);;
printf("%d\n", 12);;
printf("%d\n", 20);;
int32_t z = b;
printf("%d\n", 12);;
printf("%d\n", 30 / r);;
printf("%d\n", 20);;
int32_t aa = 51;
printf("%d\n", o);;
printf("%d\n", 31);;
printf("%d\n", 52);;
printf("%d\n", 70);;
printf("%d\n", 28);;
printf("%d\n", 18);;
int32_t ab = q - s;
int32_t ac = (t / (50 / f)) + 25;
printf("%d\n", n);;
int32_t ad = 20 + a;
printf("%d\n", 1);;
printf("%d\n", ac);;
printf("%d\n", 46);;
printf("%d\n", t);;
printf("%d\n", s + 6);;
printf("%d\n", (ac * (f * (y * (15 - (g * (((h * u) / (((70 * (((((z - b) / 43) * k) - 64) + 63)) * a) * 3)) / m)))))) - 3);;
printf("%d\n", 35 * 19);;
printf("%d\n", o / 40);;
printf("%d\n", 46);;
int32_t ae = g;
printf("%d\n", a);;
int32_t af = (27 / 46) / k;
printf("%d\n", 26);;
printf("%d\n", 82 * 36);;
int32_t ag = o - (ac - ab);
int32_t ah = 65;
printf("%d\n", 24 + (aa / ad));;
printf("%d\n", 55);;
printf("%d\n", s);;
printf("%d\n", 52);;
int32_t ai = m;
printf("%d\n", 66);;
printf("%d\n", ag - 42);;
printf("%d\n", l);;
printf("%d\n", p);;
int32_t aj = 4;
printf("%d\n", 22);;
printf("%d\n", (ai - 2) - ai);;
printf("%d\n", 27 - 54);;
printf("%d\n", 4);;
printf("%d\n", 5);;
printf("%d\n", n);;
printf("%d\n", 18);;
int32_t ak = s;
printf("%d\n", c);;
int32_t al = o;
int32_t am = 39 * ((((al * 28) * 12) * 17) - (y * 4));
int32_t an = g;
printf("%d\n", 35);;
printf("%d\n", h);;
printf("%d\n", o - 28);;
int32_t ao = ab;
int32_t ap = 18;
printf("%d\n", ag);;
printf("%d\n", 10);;
printf("%d\n", 57);;
return 0;}