#include <stdio.h>
#include <stdint.h>
int main() {
int32_t a = 130;
int32_t b = a - 32;
int32_t c = 121;
printf("%d\n", c);;
printf("%d\n", (c / 41) + 33);;
printf("%d\n", c);;
int32_t d = 3;
printf("%d\n", 50);;
printf("%d\n", 85);;
printf("%d\n", 130);;
int32_t e = 68 - (c - 18);
printf("%d\n", e);;
printf("%d\n", 21);;
printf("%d\n", e);;
printf("%d\n", 22);;
printf("%d\n", d);;
printf("%d\n", e);;
printf("%d\n", d);;
printf("%d\n", a);;
int32_t f = 19 + e;
printf("%d\n", (((c - (d - a)) + ((41 + 17) / a)) + c) - 31);;
int32_t g = b;
int32_t h = f;
printf("%d\n", 9 * 45);;
printf("%d\n", f);;
int32_t i = b;
printf("%d\n", e);;
printf("%d\n", (g / d) / (18 * f));;
int32_t j = ((d * g) + (h + 33)) + 38;
printf("%d\n", 49);;
printf("%d\n", 4);;
int32_t k = 2;
printf("%d\n", 28 / 36);;
int32_t l = h;
printf("%d\n", j / 60);;
printf("%d\n", b);;
printf("%d\n", g);;
printf("%d\n", i);;
printf("%d\n", k);;
printf("%d\n", i + 22);;
printf("%d\n", b);;
printf("%d\n", (35 - l) - (28 / a));;
printf("%d\n", f);;
printf("%d\n", 100);;
int32_t m = i;
int32_t n = b * 42;
int32_t o = 10;
printf("%d\n", 98);;
printf("%d\n", 45);;
printf("%d\n", 40);;
printf("%d\n", 20);;
int32_t p = 49;
printf("%d\n", 14 * (f + 45));;
printf("%d\n", 28);;
printf("%d\n", h);;
printf("%d\n", g);;
int32_t q = 54 * 39;
printf("%d\n", ((((((22 + 10) + 45) - ((5 / (d + 26)) + p)) - n) / k) * h) - b);;
printf("%d\n", i);;
printf("%d\n", d);;
printf("%d\n", ((18 + 61) * b) * ((((n / 15) / (11 + 4)) - (13 / j)) * h));;
printf("%d\n", d);;
int32_t r = p;
printf("%d\n", n);;
int32_t s = 1;
printf("%d\n", (g / 46) - 52);;
printf("%d\n", q);;
printf("%d\n", h);;
printf("%d\n", (29 * 39) / (n / d));;
int32_t t = g * r;
printf("%d\n", k);;
printf("%d\n", f);;
printf("%d\n", a);;
printf("%d\n", 24);;
printf("%d\n", e);;
int32_t u = b;
printf("%d\n", h);;
int32_t v = i;
printf("%d\n", p - 22);;
printf("%d\n", 33);;
printf("%d\n", 22 - 11);;
printf("%d\n", g);;
printf("%d\n", 18);;
printf("%d\n", 21);;
int32_t w = u;
printf("%d\n", 45);;
int32_t x = c;
printf("%d\n", g + e);;
printf("%d\n", 78);;
printf("%d\n", 88 * 62);;
printf("%d\n", 7);;
printf("%d\n", 22 * i);;
printf("%d\n", (w / f) * (((21 * b) + (q / p)) / (f - (38 + (9 * i)))));;
int32_t y = c;
printf("%d\n", 19);;
printf("%d\n", u);;
printf("%d\n", (((((r + i) / o) / b) + 23) + (o + (20 * (q + 38)))) - 51);;
int32_t z = v - 9;
printf("%d\n", s);;
printf("%d\n", t - p);;
printf("%d\n", 20 / c);;
int32_t aa = v * s;
int32_t ab = 77;
printf("%d\n", 26 / 6);;
int32_t ac = (((15 / (ab - (((n + 2) + ((9 / 14) * (14 + (52 * 5)))) + w))) / 23) + 53) + (4 + (68 - (3 * 4)));
printf("%d\n", s);;
int32_t ad = 9;
int32_t ae = ac - r;
printf("%d\n", ((((17 * ((ac / g) / ae)) + 5) / 45) + 73) / 20);;
printf("%d\n", p * 39);;
printf("%d\n", 62);;
int32_t af = 38;
printf("%d\n", (32 + t) - e);;
printf("%d\n", k);;
printf("%d\n", 29);;
printf("%d\n", k);;
printf("%d\n", 40);;
printf("%d\n", z);;
printf("%d\n", ac * m);;
printf("%d\n", 20 + 62);;
printf("%d\n", 34);;
printf("%d\n", (2 * m) / ((z * (66 / ((p + (11 - o)) + (34 - aa)))) + 14));;
int32_t ag = 101;
int32_t ah = ab;
printf("%d\n", 6);;
printf("%d\n", 2);;
printf("%d\n", 19);;
int32_t ai = i;
printf("%d\n", 78);;
printf("%d\n", 47);;
printf("%d\n", aa * (r - 48));;
printf("%d\n", 29);;
printf("%d\n", 5 / (ab - ((39 / ab) + ((q + 5) - x))));;
printf("%d\n", 47 * 16);;
printf("%d\n", (56 / 21) / 11);;
printf("%d\n", aa);;
printf("%d\n", 72);;
printf("%d\n", ab / 6);;
printf("%d\n", 59);;
printf("%d\n", 13);;
printf("%d\n", (70 * (g / (14 / 8))) + (22 / ((g * 6) - (((h * ((10 - 3) - ((y + (44 + ae)) * m))) + 27) * 15))));;
printf("%d\n", (39 * 44) - 100);;
printf("%d\n", m);;
printf("%d\n", i);;
printf("%d\n", 22);;
printf("%d\n", (58 * 20) * 27);;
int32_t aj = l;
printf("%d\n", 31 + (r + q));;
printf("%d\n", 33);;
printf("%d\n", 26 - h);;
int32_t ak = 38;
printf("%d\n", 4);;
printf("%d\n", 14 - 5);;
printf("%d\n", n);;
printf("%d\n", e);;
printf("%d\n", 9);;
printf("%d\n", 47 - ((((6 - (54 + 117)) - l) * ((((v + (13 * n)) / 4) * 4) - 17)) / af));;
printf("%d\n", 69);;
printf("%d\n", z);;
printf("%d\n", n);;
printf("%d\n", f);;
printf("%d\n", c / (n / (29 + 60)));;
printf("%d\n", 60 + 13);;
printf("%d\n", aj);;
int32_t al = x;
printf("%d\n", 1);;
printf("%d\n", 24);;
int32_t am = c;
printf("%d\n", w);;
printf("%d\n", 21);;
printf("%d\n", c);;
printf("%d\n", 24);;
printf("%d\n", aa);;
int32_t an = 5;
printf("%d\n", t);;
printf("%d\n", ak - (x / 38));;
printf("%d\n", (32 + (ad * 4)) - 7);;
printf("%d\n", 37 * i);;
printf("%d\n", 41);;
printf("%d\n", 36);;
printf("%d\n", 94);;
printf("%d\n", 5);;
printf("%d\n", 60 - 5);;
printf("%d\n", al * 3);;
printf("%d\n", aj);;
printf("%d\n", 1);;
printf("%d\n", ak);;
int32_t ao = (f + (((c - n) * ai) + 37)) / j;
printf("%d\n", aj);;
printf("%d\n", s);;
int32_t ap = f * 33;
int32_t aq = ad;
printf("%d\n", (((e * y) - 5) / (c / m)) * (42 * 34));;
printf("%d\n", 12 * y);;
int32_t ar = 9;
printf("%d\n", am / 34);;
printf("%d\n", an);;
printf("%d\n", 16 * 39);;
printf("%d\n", x * ((ag - 36) + (z + 28)));;
printf("%d\n", 15);;
printf("%d\n", 6);;
printf("%d\n", aa);;
printf("%d\n", (aj + k) - ah);;
int32_t as = 16;
printf("%d\n", 64);;
int32_t at = 4 / p;
printf("%d\n", k);;
printf("%d\n", ap);;
printf("%d\n", v);;
printf("%d\n", h);;
printf("%d\n", 77);;
printf("%d\n", n + 19);;
return 0;}