#include <stdio.h>
#include <stdint.h>
int main() {
printf("%d\n", ((8 / 3) + ((13 * (20 + (29 - (65 - (19 / 26))))) + 9)) * 54);;
printf("%d\n", 12);;
printf("%d\n", 16);;
int32_t a = (((3 / ((42 * ((26 - 21) + 15)) + 27)) * 25) - ((3 / (((89 - 38) + 34) / 35)) + 1)) + (60 * 6);
printf("%d\n", 3 - a);;
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", 15);;
printf("%d\n", a);;
int32_t b = (a / 32) + (54 / 45);
printf("%d\n", a);;
int32_t c = 29 - a;
printf("%d\n", 1);;
printf("%d\n", 32);;
printf("%d\n", 21);;
printf("%d\n", b);;
printf("%d\n", c / b);;
printf("%d\n", 13);;
int32_t d = a;
printf("%d\n", 26);;
printf("%d\n", b);;
printf("%d\n", d);;
printf("%d\n", 54);;
int32_t e = (32 + (45 + 6)) * a;
printf("%d\n", (e * 1) / 17);;
printf("%d\n", 5);;
printf("%d\n", d * 7);;
printf("%d\n", e);;
printf("%d\n", (((c * 68) + e) / c) + 24);;
printf("%d\n", 25);;
int32_t f = e * 14;
int32_t g = a;
printf("%d\n", 5);;
printf("%d\n", b);;
printf("%d\n", g);;
printf("%d\n", c);;
printf("%d\n", c);;
printf("%d\n", 14);;
printf("%d\n", 3);;
printf("%d\n", d);;
int32_t h = a * ((15 / d) - b);
printf("%d\n", 32 * 3);;
int32_t i = (83 * 30) - (e * (a - (34 - (1 * (13 * 82)))));
printf("%d\n", ((c - g) + g) * ((e * f) * 79));;
printf("%d\n", ((79 + 39) / d) / 43);;
int32_t j = 16 - 3;
printf("%d\n", 11);;
printf("%d\n", h);;
printf("%d\n", d);;
int32_t k = 51;
printf("%d\n", 96 - 4);;
printf("%d\n", 35);;
printf("%d\n", (12 / (52 - h)) * 62);;
printf("%d\n", 50 / e);;
printf("%d\n", 65);;
printf("%d\n", 1 - (10 - (b / b)));;
int32_t l = 5;
printf("%d\n", j);;
printf("%d\n", k - (11 * (((56 / 37) / ((39 - b) * (j + 60))) + f)));;
printf("%d\n", k);;
printf("%d\n", l);;
int32_t m = j;
printf("%d\n", 16);;
printf("%d\n", 29);;
printf("%d\n", g);;
int32_t n = 41;
printf("%d\n", f);;
int32_t o = i;
int32_t p = a;
printf("%d\n", 20);;
int32_t q = ((((a + 74) + 8) * p) + 83) + 44;
printf("%d\n", 30);;
printf("%d\n", 9);;
printf("%d\n", 22);;
printf("%d\n", j + 42);;
int32_t r = 20;
int32_t s = 3;
printf("%d\n", r);;
printf("%d\n", 22);;
int32_t t = h;
printf("%d\n", 103);;
printf("%d\n", 3 - (3 + 37));;
printf("%d\n", n);;
int32_t u = 59;
printf("%d\n", g);;
printf("%d\n", p);;
printf("%d\n", (17 + 22) - u);;
printf("%d\n", p);;
printf("%d\n", c - d);;
int32_t v = 23;
printf("%d\n", 54);;
printf("%d\n", e);;
printf("%d\n", d);;
printf("%d\n", s);;
printf("%d\n", e);;
printf("%d\n", 18);;
printf("%d\n", 21 + 18);;
printf("%d\n", e / (71 + (53 * 62)));;
printf("%d\n", 73);;
int32_t w = 51;
printf("%d\n", m);;
printf("%d\n", c);;
printf("%d\n", (28 + e) / 13);;
printf("%d\n", o);;
int32_t x = 18;
int32_t y = x;
int32_t z = 26 - i;
int32_t aa = 10;
printf("%d\n", 26);;
printf("%d\n", (7 + ((((30 - (78 + 41)) * 24) / 65) / 10)) / m);;
int32_t ab = 8;
printf("%d\n", 10);;
printf("%d\n", 53 / 19);;
printf("%d\n", v);;
int32_t ac = u;
printf("%d\n", (v / h) / 39);;
printf("%d\n", 18);;
printf("%d\n", h);;
printf("%d\n", d);;
printf("%d\n", 74);;
printf("%d\n", 26);;
int32_t ad = p;
printf("%d\n", g);;
printf("%d\n", y * w);;
int32_t ae = 69;
int32_t af = l;
printf("%d\n", t);;
printf("%d\n", 88 - ((q / (f + 117)) - ((55 + 23) + (aa / 4))));;
printf("%d\n", 10 + c);;
printf("%d\n", 52);;
printf("%d\n", 17);;
printf("%d\n", 23 - 4);;
printf("%d\n", t);;
int32_t ag = (l - v) + v;
int32_t ah = 36 - p;
printf("%d\n", f - (((91 * ag) + ae) - (aa / 37)));;
int32_t ai = af;
int32_t aj = aa - d;
printf("%d\n", l / ((g - (55 - 32)) / 8));;
int32_t ak = 96;
printf("%d\n", aa);;
printf("%d\n", k - ((23 + (g - ((((((((14 - e) - ((34 / aa) - 44)) / ab) + (4 / ak)) * 30) + f) / (29 / m)) - o))) - s));;
printf("%d\n", 14 - 13);;
printf("%d\n", 26);;
printf("%d\n", ac);;
printf("%d\n", 20);;
printf("%d\n", 107 * (15 * ag));;
printf("%d\n", z);;
printf("%d\n", 8);;
printf("%d\n", y);;
printf("%d\n", 97);;
printf("%d\n", 8);;
int32_t al = f;
printf("%d\n", 4);;
printf("%d\n", g);;
printf("%d\n", af);;
printf("%d\n", s);;
printf("%d\n", m);;
int32_t am = aj;
printf("%d\n", 42);;
int32_t an = j;
printf("%d\n", (m * 47) + (((((34 - 35) + (67 * x)) + h) - e) * i));;
printf("%d\n", (al / q) / r);;
printf("%d\n", 36);;
printf("%d\n", aa);;
printf("%d\n", 10);;
int32_t ao = am;
printf("%d\n", 23 - y);;
printf("%d\n", 37 * (z * 22));;
printf("%d\n", 17);;
printf("%d\n", 5);;
printf("%d\n", 11);;
printf("%d\n", z);;
int32_t ap = k;
printf("%d\n", 36);;
printf("%d\n", 12);;
printf("%d\n", 16);;
printf("%d\n", 17);;
printf("%d\n", y);;
printf("%d\n", aj);;
int32_t aq = (0 + j) + (53 / 12);
printf("%d\n", l);;
printf("%d\n", 40);;
printf("%d\n", 51 * (z + 62));;
printf("%d\n", l - (48 * r));;
printf("%d\n", w);;
printf("%d\n", p);;
printf("%d\n", z * 10);;
printf("%d\n", aa);;
int32_t ar = 21 * t;
printf("%d\n", aj);;
printf("%d\n", (aa - (aj + v)) / (83 / s));;
printf("%d\n", 32);;
int32_t as = 52 + (2 + s);
printf("%d\n", 25);;
printf("%d\n", 39);;
printf("%d\n", ac);;
printf("%d\n", 64);;
int32_t at = 53;
printf("%d\n", an - (ag / (14 - 40)));;
printf("%d\n", as - 55);;
printf("%d\n", 5);;
printf("%d\n", 46);;
int32_t au = (((t + (y / 42)) - 21) + (47 * ab)) / ad;
printf("%d\n", 4 - ((ak / (1 + au)) / j));;
printf("%d\n", 20 * ((44 - (aa - 43)) - 24));;
printf("%d\n", ac);;
printf("%d\n", (65 - ((t * 41) * ad)) * (ao - (((24 - aj) / 6) - (45 + v))));;
printf("%d\n", ak + 50);;
printf("%d\n", 40);;
int32_t av = c;
printf("%d\n", ai);;
int32_t aw = ad;
printf("%d\n", 23);;
printf("%d\n", 13);;
printf("%d\n", aw / aa);;
printf("%d\n", u);;
printf("%d\n", ab / q);;
printf("%d\n", ab);;
printf("%d\n", 7);;
int32_t ax = (((72 / 17) + a) / (52 - 23)) - ((z - (52 * (ap - o))) / an);
printf("%d\n", i + (ak - e));;
printf("%d\n", 36);;
printf("%d\n", ao);;
printf("%d\n", r);;
printf("%d\n", 2);;
printf("%d\n", ((32 * 13) + 45) * 4);;
int32_t ay = f;
printf("%d\n", 54);;
int32_t az = au;
printf("%d\n", (az - (56 + (z - 41))) + p);;
printf("%d\n", x);;
printf("%d\n", 52);;
printf("%d\n", 63 / 3);;
printf("%d\n", af + k);;
int32_t bb = 52;
printf("%d\n", 14);;
printf("%d\n", 42);;
printf("%d\n", 5 + an);;
int32_t bc = 62 * k;
printf("%d\n", (20 - (28 + 56)) / x);;
printf("%d\n", ay);;
return 0;}