#include <stdio.h>
#include <stdint.h>
int main() {
int32_t a = (17 * 87) / 2;
int32_t b = a;
printf("%d\n", b);;
printf("%d\n", ((a - a) + (a + a)) + b);;
printf("%d\n", (((26 * 17) * (a - 31)) + (((a - (((a + 29) * b) / 82)) + 44) * b)) / b);;
int32_t c = 22;
printf("%d\n", c * (61 * b));;
int32_t d = c;
printf("%d\n", (22 / a) - 1);;
printf("%d\n", (13 * 46) / (0 + d));;
int32_t e = (43 + 61) * (((c - 43) * 38) - 48);
printf("%d\n", 39);;
printf("%d\n", 37);;
printf("%d\n", 17 + a);;
int32_t f = 78;
printf("%d\n", 44);;
printf("%d\n", 5);;
printf("%d\n", f - (((4 * 47) * e) + f));;
printf("%d\n", 35);;
printf("%d\n", 12);;
int32_t g = e;
printf("%d\n", 69 - (23 * f));;
printf("%d\n", 11 / 104);;
int32_t h = (f + 1) + 64;
int32_t i = c / (4 - 8);
printf("%d\n", d / 21);;
printf("%d\n", 103);;
printf("%d\n", 39 + a);;
int32_t j = ((22 / (75 - (6 * i))) + (12 * h)) - (a / 20);
int32_t k = c;
int32_t l = 32;
printf("%d\n", 40);;
printf("%d\n", 92);;
printf("%d\n", h + ((l * 11) * ((a - ((a + 44) - (52 - k))) * ((b * b) - e))));;
int32_t m = 45;
int32_t n = h;
printf("%d\n", 59);;
printf("%d\n", 10);;
int32_t o = 16;
printf("%d\n", g + i);;
printf("%d\n", i);;
printf("%d\n", 22 + 43);;
int32_t p = (68 - 62) * a;
printf("%d\n", 22);;
printf("%d\n", e / g);;
printf("%d\n", 21);;
printf("%d\n", h);;
printf("%d\n", a);;
printf("%d\n", (d / n) * ((29 / (((((14 + (a / ((((m * d) - (2 * 19)) * e) / ((k - b) + (e - 2))))) * g) * 70) * ((f - h) - i)) - m)) - 23));;
printf("%d\n", 16);;
int32_t q = 37 / h;
printf("%d\n", 49);;
printf("%d\n", j);;
printf("%d\n", f);;
int32_t r = 13;
printf("%d\n", 49);;
printf("%d\n", 16);;
int32_t s = 37;
printf("%d\n", n * n);;
printf("%d\n", 23);;
int32_t t = l;
printf("%d\n", e);;
printf("%d\n", 9);;
printf("%d\n", a);;
int32_t u = f / m;
printf("%d\n", k);;
printf("%d\n", m + r);;
printf("%d\n", (b * 69) + ((b * m) - ((19 * 9) * p)));;
printf("%d\n", 13);;
printf("%d\n", 18);;
printf("%d\n", h);;
printf("%d\n", 10);;
int32_t v = u;
int32_t w = 56;
printf("%d\n", n);;
int32_t x = a;
printf("%d\n", 49);;
printf("%d\n", 13);;
printf("%d\n", ((50 - a) + (k - 11)) * h);;
printf("%d\n", 64);;
printf("%d\n", a);;
int32_t y = r - 18;
printf("%d\n", 27);;
int32_t z = 52 - d;
printf("%d\n", 7);;
int32_t aa = k;
printf("%d\n", t);;
int32_t ab = k;
printf("%d\n", o + 75);;
printf("%d\n", i);;
printf("%d\n", y);;
printf("%d\n", aa);;
int32_t ac = 5;
printf("%d\n", s);;
printf("%d\n", 8);;
printf("%d\n", 39);;
int32_t ad = 60;
printf("%d\n", 9);;
printf("%d\n", b);;
printf("%d\n", s - 10);;
printf("%d\n", o);;
printf("%d\n", u);;
printf("%d\n", m / 72);;
printf("%d\n", k);;
printf("%d\n", t / h);;
printf("%d\n", 39);;
int32_t ae = 9;
printf("%d\n", 30);;
printf("%d\n", 50 - (15 * (25 * ((ab + c) - (a - 43)))));;
printf("%d\n", 44);;
printf("%d\n", 23);;
printf("%d\n", 15 / e);;
printf("%d\n", x);;
printf("%d\n", 10);;
printf("%d\n", 10);;
printf("%d\n", 78);;
int32_t af = r;
printf("%d\n", ad);;
printf("%d\n", 32);;
printf("%d\n", 25);;
printf("%d\n", 0);;
int32_t ag = w;
int32_t ah = 21;
printf("%d\n", ad);;
printf("%d\n", k);;
printf("%d\n", ((ab / i) * (22 - ((d + (n / 24)) * (l + ah)))) + 16);;
return 0;}