#include <stdio.h>
#include <stdint.h>
int main() {
printf("%d\n", 38);;
int32_t a = 7;
int32_t b = a;
printf("%d\n", 46);;
printf("%d\n", a / b);;
printf("%d\n", 2 * a);;
printf("%d\n", a);;
printf("%d\n", 35);;
int32_t c = 31;
printf("%d\n", b - (52 - c));;
int32_t d = 67 - (2 + (c + c));
int32_t e = b;
printf("%d\n", b);;
int32_t f = c;
int32_t g = 1;
printf("%d\n", 80);;
printf("%d\n", g / ((e - 41) - (e - (8 + (101 / g)))));;
printf("%d\n", 18);;
printf("%d\n", 52);;
int32_t h = d - 35;
printf("%d\n", f);;
int32_t i = e * 76;
int32_t j = 88;
printf("%d\n", j - c);;
int32_t k = 64;
printf("%d\n", 27);;
printf("%d\n", f);;
printf("%d\n", 37);;
int32_t l = 18;
printf("%d\n", 44);;
printf("%d\n", d * 60);;
printf("%d\n", h);;
printf("%d\n", 39 * g);;
printf("%d\n", 11 / l);;
int32_t m = l;
int32_t n = e;
int32_t o = f * c;
int32_t p = a;
printf("%d\n", i);;
int32_t q = g;
printf("%d\n", m);;
printf("%d\n", 22);;
int32_t r = g;
printf("%d\n", 8);;
printf("%d\n", f);;
int32_t s = o - h;
printf("%d\n", 60);;
int32_t t = 28;
int32_t u = o;
printf("%d\n", f - 2);;
int32_t v = r;
printf("%d\n", 3);;
printf("%d\n", 37 / q);;
printf("%d\n", v);;
printf("%d\n", f);;
printf("%d\n", 15 + q);;
printf("%d\n", l);;
printf("%d\n", h);;
int32_t w = 15;
printf("%d\n", b);;
printf("%d\n", a);;
printf("%d\n", m);;
printf("%d\n", 13);;
printf("%d\n", 2 * a);;
printf("%d\n", 19 + (q + 31));;
printf("%d\n", 23);;
printf("%d\n", b);;
printf("%d\n", r);;
printf("%d\n", 6);;
printf("%d\n", 18);;
printf("%d\n", g);;
printf("%d\n", 6);;
printf("%d\n", j + 49);;
int32_t x = 18;
printf("%d\n", a * 60);;
printf("%d\n", u);;
printf("%d\n", ((48 / l) + i) / (79 / 12));;
printf("%d\n", x);;
printf("%d\n", u);;
printf("%d\n", 83);;
printf("%d\n", d);;
printf("%d\n", 10);;
printf("%d\n", v);;
printf("%d\n", f - (((s * 36) * (r - j)) * (10 + 14)));;
printf("%d\n", (21 - 12) + w);;
printf("%d\n", x);;
printf("%d\n", d);;
printf("%d\n", 69);;
printf("%d\n", 76);;
printf("%d\n", r);;
printf("%d\n", 35);;
printf("%d\n", g);;
printf("%d\n", j);;
printf("%d\n", b);;
int32_t y = i;
int32_t z = h / 29;
printf("%d\n", 23);;
printf("%d\n", 9);;
printf("%d\n", s);;
printf("%d\n", r);;
return 0;}