#include <stdio.h>
#include <stdint.h>
int main() {
int32_t a = 10;
printf("%d\n", 50);;
printf("%d\n", a);;
printf("%d\n", 10);;
int32_t b = 5 + (5 - 9);
printf("%d\n", 14 - 6);;
int32_t c = 21;
int32_t d = c;
printf("%d\n", 15);;
printf("%d\n", 33);;
printf("%d\n", d);;
int32_t e = 29;
printf("%d\n", 4 + 24);;
printf("%d\n", a);;
printf("%d\n", c / e);;
printf("%d\n", 34);;
printf("%d\n", 21 - ((b + 22) + b));;
int32_t f = 47 + c;
printf("%d\n", 14);;
printf("%d\n", 1);;
printf("%d\n", 52 - (e / 55));;
printf("%d\n", (e / d) / e);;
int32_t g = (f * a) - 16;
printf("%d\n", 47);;
printf("%d\n", 8);;
int32_t h = 58;
printf("%d\n", g / h);;
printf("%d\n", 2);;
printf("%d\n", h + ((0 * ((d / b) / (e + (b + b)))) / 109));;
printf("%d\n", 3);;
int32_t i = e * f;
printf("%d\n", 88);;
printf("%d\n", 66);;
printf("%d\n", (b / a) / c);;
printf("%d\n", 47);;
int32_t j = 91;
printf("%d\n", 29);;
int32_t k = 2;
int32_t l = e + 57;
printf("%d\n", 48);;
printf("%d\n", a / (30 + 56));;
printf("%d\n", h);;
int32_t m = h;
printf("%d\n", (h + (57 * ((((e * g) * h) + b) * ((13 + 14) - d)))) / h);;
printf("%d\n", 18 * (14 * 17));;
int32_t n = 48;
printf("%d\n", l);;
printf("%d\n", j);;
printf("%d\n", l - 67);;
printf("%d\n", i);;
printf("%d\n", j);;
printf("%d\n", l / 27);;
printf("%d\n", l - (l / (i / n)));;
int32_t o = (48 / 23) * e;
printf("%d\n", i);;
printf("%d\n", a);;
int32_t p = (87 / i) * 26;
int32_t q = n;
printf("%d\n", e);;
int32_t r = (b * (h * 25)) / 12;
printf("%d\n", 28 - d);;
printf("%d\n", 41);;
printf("%d\n", n);;
int32_t s = (e * g) + 2;
printf("%d\n", 21);;
printf("%d\n", i);;
int32_t t = 43;
int32_t u = a;
printf("%d\n", 12);;
printf("%d\n", 35 + 19);;
int32_t v = f;
printf("%d\n", f + (18 + p));;
printf("%d\n", l);;
printf("%d\n", r);;
printf("%d\n", b);;
printf("%d\n", (5 + v) + 46);;
printf("%d\n", (v / k) / n);;
printf("%d\n", v + 20);;
int32_t w = 49 + c;
printf("%d\n", 26);;
printf("%d\n", 27);;
printf("%d\n", 32);;
printf("%d\n", ((m / (10 + 5)) + a) / 8);;
int32_t x = 7 / (j + (k / 39));
printf("%d\n", n);;
printf("%d\n", (g / 65) * 3);;
int32_t y = (a - 11) - r;
printf("%d\n", 0);;
printf("%d\n", 13);;
printf("%d\n", (i * 71) + j);;
printf("%d\n", 11 / 20);;
printf("%d\n", ((27 / v) * 74) - 12);;
printf("%d\n", 4 / 51);;
int32_t z = 31;
int32_t aa = (5 + (3 - 14)) / y;
printf("%d\n", h);;
printf("%d\n", (2 * 30) + w);;
return 0;}