#include <stdio.h>
#include <stdint.h>
int main() {
int32_t a = 37;
printf("%d\n", a * (((a - a) - ((a + (a / ((((30 * a) + 72) / 2) * a))) - a)) + (a - a)));;
printf("%d\n", a);;
int32_t b = a - 12;
int32_t c = ((b * b) * 26) + (b + 11);
printf("%d\n", c);;
printf("%d\n", c);;
printf("%d\n", 9);;
printf("%d\n", b);;
printf("%d\n", c);;
printf("%d\n", a);;
int32_t d = 9 - 55;
int32_t e = a * a;
printf("%d\n", 61);;
printf("%d\n", (12 + 57) + 34);;
int32_t f = 79;
printf("%d\n", a);;
printf("%d\n", 85);;
printf("%d\n", e);;
printf("%d\n", e);;
printf("%d\n", 86);;
int32_t g = (b - 6) + c;
printf("%d\n", 28 / 15);;
printf("%d\n", f - 4);;
printf("%d\n", ((e * 47) + 24) - a);;
printf("%d\n", d);;
printf("%d\n", 17);;
printf("%d\n", g / (((((51 + 3) / 33) - d) / b) * a));;
printf("%d\n", 18);;
printf("%d\n", 56);;
printf("%d\n", f);;
printf("%d\n", c * f);;
printf("%d\n", a * (65 * e));;
printf("%d\n", 1);;
printf("%d\n", e / 2);;
printf("%d\n", a);;
printf("%d\n", 16);;
int32_t h = e;
int32_t i = 28 / g;
int32_t j = 12 * b;
printf("%d\n", g);;
printf("%d\n", j);;
int32_t k = a * 43;
printf("%d\n", c / 14);;
printf("%d\n", 11);;
printf("%d\n", g * 19);;
printf("%d\n", i);;
printf("%d\n", j);;
int32_t l = 3;
int32_t m = (a * 73) * (67 - d);
printf("%d\n", 66 + ((((36 - 60) / ((k * ((j / l) - l)) + k)) * i) * 18));;
printf("%d\n", 29);;
printf("%d\n", 64);;
int32_t n = 8 + (16 * 21);
int32_t o = (l * ((m + 15) * l)) - c;
printf("%d\n", 33);;
printf("%d\n", m);;
printf("%d\n", (9 + ((48 + 18) + 26)) - (n * (44 / (24 / l))));;
int32_t p = 56;
printf("%d\n", b * p);;
printf("%d\n", 56);;
int32_t q = 10;
printf("%d\n", (8 + 49) / l);;
printf("%d\n", 70);;
printf("%d\n", 26);;
printf("%d\n", 4);;
printf("%d\n", l);;
int32_t r = l;
printf("%d\n", 53 - (((e + 81) - e) + 43));;
printf("%d\n", o);;
int32_t s = 38 / (a - 24);
int32_t t = b;
printf("%d\n", i);;
int32_t u = 46;
printf("%d\n", 68);;
printf("%d\n", 4 * h);;
printf("%d\n", t);;
int32_t v = 47;
printf("%d\n", 11);;
printf("%d\n", 39);;
printf("%d\n", t);;
printf("%d\n", e);;
printf("%d\n", 80 * o);;
printf("%d\n", c + 23);;
printf("%d\n", 13);;
printf("%d\n", 5);;
printf("%d\n", l);;
printf("%d\n", s);;
int32_t w = f;
int32_t x = 20;
printf("%d\n", 14);;
int32_t y = 17;
printf("%d\n", p);;
int32_t z = q * d;
printf("%d\n", o);;
printf("%d\n", 50);;
printf("%d\n", a / u);;
printf("%d\n", 53);;
printf("%d\n", r);;
printf("%d\n", 61);;
printf("%d\n", 16 - 14);;
int32_t aa = t;
int32_t ab = 13;
printf("%d\n", w);;
printf("%d\n", s);;
int32_t ac = c / e;
printf("%d\n", f);;
printf("%d\n", 47);;
int32_t ad = 40;
printf("%d\n", z);;
printf("%d\n", ad);;
printf("%d\n", o);;
printf("%d\n", 22);;
printf("%d\n", k);;
printf("%d\n", 87);;
printf("%d\n", 20);;
printf("%d\n", (h + 40) + j);;
printf("%d\n", v * (h + 33));;
printf("%d\n", e);;
int32_t ae = 53;
printf("%d\n", v);;
printf("%d\n", 57);;
printf("%d\n", 45);;
printf("%d\n", d);;
printf("%d\n", 20);;
int32_t af = 7;
printf("%d\n", 81);;
printf("%d\n", 29);;
int32_t ag = o;
int32_t ah = 95;
printf("%d\n", 70);;
int32_t ai = g;
printf("%d\n", 40 - 23);;
printf("%d\n", n);;
printf("%d\n", 18);;
printf("%d\n", j);;
printf("%d\n", (1 / e) / 49);;
printf("%d\n", 9 / (22 - 17));;
printf("%d\n", g);;
printf("%d\n", ((i + 61) / 21) + 47);;
printf("%d\n", 5 + 58);;
printf("%d\n", 33);;
int32_t aj = 3 * k;
printf("%d\n", 40);;
return 0;}