#include <stdio.h>
#include <stdint.h>
int main() {
printf("%d\n", 54);;
printf("%d\n", ((1 + (((5 / 72) / ((60 + 69) * 13)) / 15)) - (50 + 26)) * 9);;
int32_t a = (72 * ((((((((14 / (61 + ((30 * (57 / 10)) / 33))) + 37) + (52 / (33 * ((23 / 34) - 24)))) + (((9 * 50) + ((14 + (2 - ((10 / (28 - (63 / 35))) - ((55 / 58) - ((6 + 17) * 35))))) / 19)) * (16 + 20))) + 27) / 74) - 33) - 1)) / 61;
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", 7);;
printf("%d\n", a + 40);;
printf("%d\n", (51 - a) / 13);;
int32_t b = a;
printf("%d\n", 92 / a);;
printf("%d\n", a);;
int32_t c = ((a + b) * b) + a;
printf("%d\n", 5);;
printf("%d\n", b);;
printf("%d\n", 12);;
int32_t d = (10 * (37 / a)) + b;
int32_t e = 20;
printf("%d\n", 29);;
printf("%d\n", 20);;
int32_t f = c;
printf("%d\n", 6);;
int32_t g = (13 / (((((((b - b) / e) / 73) - a) + 39) + ((4 * d) * (b / 51))) / a)) * 41;
printf("%d\n", c - g);;
printf("%d\n", 12);;
printf("%d\n", 59 + f);;
printf("%d\n", 4);;
printf("%d\n", b - (d * 22));;
int32_t h = g;
printf("%d\n", 4 / (d + ((52 / h) * 14)));;
printf("%d\n", f - g);;
printf("%d\n", (((e + b) / d) - 8) / (22 + 63));;
printf("%d\n", 39);;
int32_t i = 13;
printf("%d\n", ((28 * 16) / d) / 19);;
printf("%d\n", h);;
printf("%d\n", a * (c * (i + ((f + 6) - 10))));;
printf("%d\n", 12);;
printf("%d\n", 44);;
int32_t j = e;
int32_t k = d;
printf("%d\n", i);;
int32_t l = j;
printf("%d\n", f);;
int32_t m = 7;
printf("%d\n", f);;
printf("%d\n", l);;
int32_t n = ((61 / (23 + e)) * k) - 56;
printf("%d\n", ((i - d) * m) + 22);;
printf("%d\n", ((17 / 27) * l) / (25 + 35));;
int32_t o = 27;
printf("%d\n", 40 + (16 + o));;
printf("%d\n", 11);;
printf("%d\n", 41 * b);;
printf("%d\n", 11);;
printf("%d\n", m);;
printf("%d\n", m);;
printf("%d\n", a);;
printf("%d\n", 57);;
printf("%d\n", 71);;
printf("%d\n", 25);;
printf("%d\n", c / 86);;
int32_t p = 77 * l;
int32_t q = k;
int32_t r = 3;
printf("%d\n", r + (a + l));;
printf("%d\n", 5);;
int32_t s = j - 40;
int32_t t = s;
printf("%d\n", t);;
printf("%d\n", d);;
printf("%d\n", e);;
printf("%d\n", q);;
printf("%d\n", l);;
printf("%d\n", 9);;
printf("%d\n", 51);;
printf("%d\n", q);;
printf("%d\n", l + 45);;
printf("%d\n", i);;
printf("%d\n", j);;
printf("%d\n", r + (g - 86));;
printf("%d\n", s);;
printf("%d\n", 23);;
printf("%d\n", b);;
printf("%d\n", 65);;
printf("%d\n", 27);;
printf("%d\n", 13 / (8 / m));;
printf("%d\n", 18);;
printf("%d\n", 73);;
printf("%d\n", k);;
int32_t u = b;
int32_t v = h;
printf("%d\n", r);;
int32_t w = u;
printf("%d\n", 5);;
printf("%d\n", 16);;
printf("%d\n", (10 + 11) * b);;
printf("%d\n", u);;
printf("%d\n", s - 8);;
int32_t x = r;
printf("%d\n", (13 / i) * 75);;
printf("%d\n", u);;
printf("%d\n", 52);;
int32_t y = (((((x / ((((22 - 8) * ((a + (j / 40)) - ((d / (h - ((8 * f) / 53))) + g))) + 15) * 8)) - w) / 87) / 30) - (p / k)) / 39;
printf("%d\n", (2 * ((l - d) + g)) - (s / f));;
printf("%d\n", 38 * r);;
printf("%d\n", e);;
printf("%d\n", 27);;
printf("%d\n", g);;
int32_t z = 55;
printf("%d\n", 7);;
int32_t aa = 29;
int32_t ab = a / ((y - o) - t);
printf("%d\n", 32);;
printf("%d\n", 16 * 101);;
printf("%d\n", f / c);;
int32_t ac = l;
int32_t ad = z / 32;
printf("%d\n", ac);;
printf("%d\n", ac);;
int32_t ae = aa;
printf("%d\n", ad);;
printf("%d\n", 2);;
int32_t af = w * ad;
printf("%d\n", ae);;
int32_t ag = (aa - k) - u;
printf("%d\n", 4);;
printf("%d\n", t);;
int32_t ah = 76;
printf("%d\n", (53 + ((((((t - ((d * u) / (o - p))) - 26) + 16) * 44) * w) - ((t / 41) - (13 / 38)))) + ((75 - ((ah + ad) * 57)) / (61 * ((ab / u) - 48))));;
printf("%d\n", 28);;
printf("%d\n", ((((e / ((73 - aa) + (30 * af))) / (44 - 60)) * (ad - (g - (15 + 56)))) * 5) * 24);;
printf("%d\n", 14 + (16 - 40));;
int32_t ai = 68;
int32_t aj = 66;
printf("%d\n", e);;
int32_t ak = ae;
int32_t al = z;
printf("%d\n", ab);;
int32_t am = ag - (26 - 27);
printf("%d\n", aa);;
int32_t an = z;
printf("%d\n", s);;
printf("%d\n", aj);;
printf("%d\n", ab);;
printf("%d\n", 30);;
printf("%d\n", (32 * 76) * ab);;
int32_t ao = 1 / 45;
printf("%d\n", ac);;
int32_t ap = r;
printf("%d\n", e);;
printf("%d\n", n);;
printf("%d\n", 26);;
printf("%d\n", aa);;
printf("%d\n", r);;
printf("%d\n", (ad / ((ah / (16 - ((ab * k) + 18))) - 26)) / ak);;
printf("%d\n", 13 * 80);;
int32_t aq = 21 - 20;
printf("%d\n", 44 * 67);;
printf("%d\n", 29);;
printf("%d\n", 52);;
printf("%d\n", 41);;
printf("%d\n", ah - d);;
printf("%d\n", 56);;
int32_t ar = h / (((((47 + r) - ao) - ((ae - 80) + (37 - f))) * (46 * (26 + a))) + (aq - 7));
int32_t as = 66;
printf("%d\n", 19 - 4);;
printf("%d\n", 13);;
int32_t at = (s * 29) / 41;
printf("%d\n", 60);;
printf("%d\n", x);;
printf("%d\n", w + 32);;
printf("%d\n", ao);;
printf("%d\n", 30);;
printf("%d\n", at + 37);;
int32_t au = j;
printf("%d\n", 25);;
printf("%d\n", aa);;
printf("%d\n", 35);;
printf("%d\n", 36);;
printf("%d\n", (ap / ((al - ((j + 64) - 45)) + 11)) / c);;
int32_t av = (27 * ((an - ai) / g)) * ((z / au) - ah);
int32_t aw = 61 - 10;
printf("%d\n", 68 - ((ap + 2) * 29));;
printf("%d\n", av);;
printf("%d\n", 15);;
printf("%d\n", an - ((59 - (89 / ((4 - p) / ((13 + au) + 4)))) + 122));;
printf("%d\n", y);;
int32_t ax = r * x;
printf("%d\n", h);;
printf("%d\n", c);;
printf("%d\n", e);;
printf("%d\n", 4 / ((51 - ((2 / 11) + ((9 * (12 * o)) - l))) * (ai / 8)));;
printf("%d\n", 9);;
printf("%d\n", k - ((86 - l) + 5));;
printf("%d\n", 15 * 4);;
printf("%d\n", (24 * (ac / 5)) * 20);;
printf("%d\n", l);;
printf("%d\n", av + 7);;
int32_t ay = (af / (30 * 5)) * s;
printf("%d\n", 16 + ay);;
printf("%d\n", 20);;
printf("%d\n", 30 * av);;
int32_t az = m - (aw * af);
printf("%d\n", am);;
printf("%d\n", 12);;
printf("%d\n", ah);;
printf("%d\n", y);;
int32_t bb = k * au;
printf("%d\n", (((r - aq) / 53) - 1) + c);;
printf("%d\n", (81 / az) + ap);;
printf("%d\n", 84);;
printf("%d\n", k);;
printf("%d\n", x);;
printf("%d\n", ac);;
printf("%d\n", 39 / (aj * 35));;
printf("%d\n", 25);;
int32_t bc = ap;
printf("%d\n", 67);;
printf("%d\n", ax);;
int32_t bd = w;
printf("%d\n", (ak + 0) + (47 + 10));;
printf("%d\n", 62);;
printf("%d\n", 30);;
printf("%d\n", x);;
printf("%d\n", 36);;
printf("%d\n", 30 / 35);;
printf("%d\n", s);;
printf("%d\n", ap);;
return 0;}