#include <stdio.h>
#include <stdint.h>
int main() {
printf("%d\n", (78 * (50 / 4)) - ((19 * ((44 / 6) + (32 - (6 - 0)))) - 84));;
printf("%d\n", 47);;
printf("%d\n", 19 / (127 / 71));;
printf("%d\n", 22);;
int32_t a = (((65 * (5 * (11 / 52))) + (9 * 27)) / 18) / (55 / 26);
printf("%d\n", (a / a) * 22);;
printf("%d\n", (35 / (49 + 24)) - (57 * (a - a)));;
printf("%d\n", 19);;
printf("%d\n", 22);;
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", 31 - a);;
printf("%d\n", 20);;
printf("%d\n", 25);;
printf("%d\n", 90);;
printf("%d\n", 38);;
int32_t b = 22;
int32_t c = 41 * (a + (b / b));
printf("%d\n", 9);;
int32_t d = 16;
printf("%d\n", 3);;
printf("%d\n", 19);;
printf("%d\n", 34 - (b + a));;
printf("%d\n", b - d);;
printf("%d\n", 11);;
printf("%d\n", 8);;
printf("%d\n", a);;
int32_t e = c;
int32_t f = a + e;
printf("%d\n", 3);;
printf("%d\n", 49);;
printf("%d\n", f);;
printf("%d\n", b);;
int32_t g = b;
printf("%d\n", d);;
int32_t h = (60 - e) - ((d * f) / c);
printf("%d\n", 13);;
printf("%d\n", 35);;
printf("%d\n", 14 + h);;
int32_t i = d;
printf("%d\n", 19);;
int32_t j = 2;
int32_t k = 10;
printf("%d\n", h);;
printf("%d\n", 27);;
int32_t l = j;
int32_t m = 19;
printf("%d\n", i - (c * d));;
int32_t n = 19 * 19;
int32_t o = f / 36;
printf("%d\n", 32);;
printf("%d\n", e);;
printf("%d\n", b + m);;
printf("%d\n", e - (43 * 10));;
printf("%d\n", ((2 + 48) - k) / 87);;
int32_t p = 12;
int32_t q = 65;
printf("%d\n", k);;
printf("%d\n", n);;
printf("%d\n", 8);;
int32_t r = 45;
int32_t s = j * q;
int32_t t = 31;
printf("%d\n", 41);;
printf("%d\n", 20 * (((l + o) * (44 + (((51 / n) * b) + o))) / 30));;
int32_t u = c;
printf("%d\n", g * 30);;
printf("%d\n", ((u / r) * s) * m);;
printf("%d\n", i);;
int32_t v = 51 + (m + ((e / a) - ((41 * (p * (((12 / 29) / d) * 51))) + 9)));
printf("%d\n", j - 54);;
int32_t w = v;
int32_t x = 39;
int32_t y = 44;
printf("%d\n", o + h);;
printf("%d\n", (n * u) * 3);;
printf("%d\n", 5);;
printf("%d\n", u);;
printf("%d\n", 12);;
printf("%d\n", 130);;
printf("%d\n", b);;
printf("%d\n", 8);;
printf("%d\n", 65);;
printf("%d\n", l);;
printf("%d\n", 15);;
printf("%d\n", 26 + 3);;
printf("%d\n", 11);;
printf("%d\n", t);;
int32_t z = b;
int32_t aa = 7;
printf("%d\n", n);;
printf("%d\n", 13);;
printf("%d\n", r);;
printf("%d\n", (c - b) / (((i * e) + (11 + p)) / ((20 - x) + c)));;
int32_t ab = 7;
printf("%d\n", 17);;
printf("%d\n", u);;
printf("%d\n", 89);;
printf("%d\n", i);;
printf("%d\n", 0);;
printf("%d\n", n - 26);;
printf("%d\n", r);;
printf("%d\n", ((k - 3) - 19) * 3);;
printf("%d\n", e);;
printf("%d\n", n * (c * (33 * 49)));;
printf("%d\n", q);;
printf("%d\n", s);;
printf("%d\n", ((w + 28) * (25 / (e + z))) - 59);;
int32_t ac = 63;
int32_t ad = k;
printf("%d\n", ((d + z) + 79) + ad);;
printf("%d\n", 15 + m);;
printf("%d\n", o);;
int32_t ae = m + 3;
int32_t af = t;
printf("%d\n", p);;
int32_t ag = k - (n / k);
int32_t ah = v;
printf("%d\n", (ab + (((g + 3) / (62 + c)) - ((11 * j) - (37 + 57)))) - (7 + 32));;
int32_t ai = m;
printf("%d\n", x);;
printf("%d\n", k);;
printf("%d\n", 24 - v);;
printf("%d\n", 36 * 28);;
printf("%d\n", 79);;
printf("%d\n", 27);;
printf("%d\n", 20 - ah);;
printf("%d\n", ac);;
printf("%d\n", 49);;
printf("%d\n", (54 - (13 + (z / a))) * i);;
printf("%d\n", 2);;
printf("%d\n", 14);;
printf("%d\n", l);;
printf("%d\n", 21);;
printf("%d\n", 51);;
printf("%d\n", ag);;
printf("%d\n", 46);;
printf("%d\n", 25);;
int32_t aj = 16;
printf("%d\n", 23);;
printf("%d\n", 54);;
printf("%d\n", j);;
printf("%d\n", h);;
printf("%d\n", v + (67 + p));;
printf("%d\n", 35 - l);;
printf("%d\n", 89);;
printf("%d\n", 16);;
printf("%d\n", 5 - 2);;
printf("%d\n", 5);;
int32_t ak = e - 10;
printf("%d\n", x - (v - (22 / 74)));;
int32_t al = g;
int32_t am = ad;
printf("%d\n", o);;
printf("%d\n", 17);;
printf("%d\n", v);;
printf("%d\n", h);;
printf("%d\n", af);;
printf("%d\n", p);;
int32_t an = 1;
printf("%d\n", 16);;
printf("%d\n", ag);;
printf("%d\n", b);;
printf("%d\n", 1 / (16 * 59));;
int32_t ao = c;
printf("%d\n", 27 * (54 + s));;
printf("%d\n", j);;
printf("%d\n", b);;
printf("%d\n", 23);;
printf("%d\n", 7);;
printf("%d\n", 10);;
printf("%d\n", a);;
printf("%d\n", ab);;
printf("%d\n", ab - ((an / 27) / (3 - p)));;
printf("%d\n", 2);;
printf("%d\n", 36);;
printf("%d\n", r);;
printf("%d\n", 22);;
printf("%d\n", s);;
printf("%d\n", 51);;
printf("%d\n", 11 * 29);;
printf("%d\n", 27);;
int32_t ap = m;
printf("%d\n", 59);;
printf("%d\n", am);;
printf("%d\n", 15);;
printf("%d\n", m / 51);;
printf("%d\n", af);;
printf("%d\n", d);;
printf("%d\n", ad);;
printf("%d\n", 17 - 28);;
printf("%d\n", (1 / h) + c);;
printf("%d\n", 8);;
int32_t aq = 2;
return 0;}