#include <stdio.h>
#include <stdint.h>
int main() {
printf("%d\n", (78 + 75) * 12);;
int32_t a = 5;
int32_t b = a;
printf("%d\n", 22);;
printf("%d\n", (a * (b + (((28 / (10 + ((72 - (b * a)) / (b * (a + 12))))) + a) + (a * b)))) - (65 - 22));;
printf("%d\n", 11);;
int32_t c = a - 6;
printf("%d\n", 10);;
printf("%d\n", c);;
printf("%d\n", a * (37 - c));;
printf("%d\n", 23);;
int32_t d = 7 + b;
printf("%d\n", (27 / (25 * d)) / (c - ((5 * b) / b)));;
printf("%d\n", a);;
printf("%d\n", b);;
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", a - (13 / 67));;
printf("%d\n", d + b);;
printf("%d\n", 24);;
printf("%d\n", c);;
printf("%d\n", 8);;
int32_t e = a;
int32_t f = c;
int32_t g = d;
int32_t h = g;
printf("%d\n", f / 35);;
printf("%d\n", f + b);;
printf("%d\n", 8);;
printf("%d\n", 63);;
printf("%d\n", e);;
printf("%d\n", 107 + f);;
int32_t i = 89 + 8;
int32_t j = d;
printf("%d\n", j);;
printf("%d\n", h);;
int32_t k = f + ((f - c) / (((13 * a) * 55) * i));
printf("%d\n", 63);;
int32_t l = j;
printf("%d\n", 61);;
printf("%d\n", 14);;
printf("%d\n", h);;
printf("%d\n", e);;
printf("%d\n", 35);;
printf("%d\n", (13 * 57) - g);;
int32_t m = 36;
printf("%d\n", 75 / l);;
printf("%d\n", 8);;
printf("%d\n", b);;
printf("%d\n", 74);;
printf("%d\n", 30);;
printf("%d\n", i);;
printf("%d\n", ((4 - ((14 - f) - m)) + l) / 9);;
printf("%d\n", 4);;
int32_t n = 65 - 38;
printf("%d\n", 29 - 4);;
printf("%d\n", ((m / 13) / l) - 10);;
printf("%d\n", f);;
printf("%d\n", f);;
printf("%d\n", b);;
printf("%d\n", 45 - b);;
int32_t o = 8;
printf("%d\n", 4 / a);;
printf("%d\n", l / 45);;
printf("%d\n", m);;
printf("%d\n", 1);;
printf("%d\n", 58);;
printf("%d\n", 2);;
int32_t p = 22;
int32_t q = 107;
printf("%d\n", 61);;
printf("%d\n", g * p);;
printf("%d\n", 53);;
printf("%d\n", 4);;
int32_t r = 26 / o;
int32_t s = o;
int32_t t = i;
printf("%d\n", (((((i / b) + (h - q)) / (57 * t)) - (c - g)) + 21) * 0);;
printf("%d\n", 4);;
int32_t u = 37;
printf("%d\n", 37 / (o - a));;
printf("%d\n", 57);;
int32_t v = 12;
int32_t w = 18;
printf("%d\n", 21 * d);;
int32_t x = f;
printf("%d\n", f);;
printf("%d\n", o);;
printf("%d\n", i);;
printf("%d\n", 60);;
printf("%d\n", j - 9);;
printf("%d\n", j);;
int32_t y = 34;
printf("%d\n", 16);;
printf("%d\n", 17);;
int32_t z = m;
printf("%d\n", 20);;
printf("%d\n", m);;
printf("%d\n", s);;
printf("%d\n", 9);;
printf("%d\n", 21 - c);;
int32_t aa = 33;
printf("%d\n", 18);;
int32_t ab = ((((u / (((j + i) / q) - n)) - 26) + 72) * v) - 33;
printf("%d\n", e + ((84 - 11) / f));;
printf("%d\n", 62 + 16);;
printf("%d\n", 11 / 31);;
printf("%d\n", 2);;
printf("%d\n", 18);;
printf("%d\n", 21);;
printf("%d\n", 51);;
printf("%d\n", z / 53);;
printf("%d\n", 1);;
printf("%d\n", 3);;
int32_t ac = m;
printf("%d\n", 38);;
int32_t ad = 20 * 8;
printf("%d\n", 26);;
printf("%d\n", e);;
printf("%d\n", 34);;
int32_t ae = 53 - 57;
int32_t af = (30 - 37) / ((ae / 5) - (19 / r));
int32_t ag = 26 - 33;
printf("%d\n", 1 + ad);;
printf("%d\n", l);;
printf("%d\n", ac * 72);;
printf("%d\n", (88 - ((j + af) * f)) - 50);;
int32_t ah = b * x;
printf("%d\n", 48);;
printf("%d\n", ((19 / x) / (l + ((y + (33 + 6)) + 61))) + (ae / ((e - aa) * (b + 2))));;
int32_t ai = 55;
int32_t aj = (ae / x) * ac;
printf("%d\n", w);;
int32_t ak = q;
printf("%d\n", 26);;
printf("%d\n", 44 - u);;
printf("%d\n", g);;
int32_t al = v;
printf("%d\n", 80);;
printf("%d\n", q);;
int32_t am = ag / 14;
printf("%d\n", d);;
int32_t an = j;
int32_t ao = 40 / (p + ab);
printf("%d\n", 68);;
int32_t ap = ai;
return 0;}