#include <stdio.h>
#include <stdint.h>
int main() {
printf("%d\n", 7);;
int32_t a = 26;
int32_t b = a;
printf("%d\n", ((7 * b) - ((a - (14 * (36 - a))) + 25)) + (41 - (5 * 21)));;
printf("%d\n", b);;
int32_t c = (a / b) - 33;
int32_t d = a;
printf("%d\n", b);;
int32_t e = a;
int32_t f = 45;
printf("%d\n", (b + 37) * 1);;
printf("%d\n", 5);;
printf("%d\n", 58 / c);;
printf("%d\n", 62);;
int32_t g = (36 - ((c - 49) - d)) - 29;
printf("%d\n", e);;
printf("%d\n", 27);;
printf("%d\n", 8);;
printf("%d\n", c);;
printf("%d\n", 20);;
printf("%d\n", 73);;
int32_t h = 25;
printf("%d\n", 55);;
printf("%d\n", a);;
printf("%d\n", h);;
printf("%d\n", 8);;
printf("%d\n", (e + 17) * (((a * 15) + ((11 - 5) + g)) * 3));;
printf("%d\n", g / h);;
printf("%d\n", b);;
printf("%d\n", 8);;
printf("%d\n", g);;
printf("%d\n", 81);;
printf("%d\n", d);;
printf("%d\n", 18);;
int32_t i = 54 / (10 * c);
printf("%d\n", b);;
printf("%d\n", 75);;
printf("%d\n", i);;
int32_t j = 10;
printf("%d\n", 29);;
printf("%d\n", 75);;
printf("%d\n", i);;
int32_t k = i;
printf("%d\n", 6);;
printf("%d\n", a / ((a - 59) - (a - b)));;
printf("%d\n", (e / g) - i);;
printf("%d\n", 14);;
printf("%d\n", j - 2);;
int32_t l = f;
printf("%d\n", 23 * 68);;
printf("%d\n", 38);;
printf("%d\n", 3);;
printf("%d\n", 69 * l);;
return 0;}