#include <stdio.h>
#include <stdint.h>
int main() {
int32_t a = 7 + (61 + 10);
printf("%d\n", 21);;
int32_t b = 23 + 121;
int32_t c = 14;
printf("%d\n", c);;
printf("%d\n", 101);;
printf("%d\n", (c / 49) - (3 + 94));;
printf("%d\n", a);;
printf("%d\n", c + 17);;
printf("%d\n", 29);;
int32_t d = b;
printf("%d\n", (65 - (c - b)) - 16);;
printf("%d\n", 2 - b);;
printf("%d\n", (18 + d) * a);;
int32_t e = 18;
printf("%d\n", 69);;
printf("%d\n", c);;
printf("%d\n", 26);;
printf("%d\n", (48 - 8) - 23);;
printf("%d\n", 60);;
printf("%d\n", b);;
printf("%d\n", ((15 + (d / c)) + (43 - d)) * ((((116 / 66) / 120) * (7 * (d * ((c + (37 + 24)) / b)))) / b));;
printf("%d\n", (3 / ((13 + (50 - (((b / (72 - 14)) / (((12 + 12) + (17 / a)) + e)) - (20 + ((d - 26) + 10))))) + 12)) - 20);;
printf("%d\n", a / d);;
int32_t f = c;
printf("%d\n", a);;
int32_t g = 82;
printf("%d\n", g);;
printf("%d\n", 12 * 11);;
printf("%d\n", f);;
printf("%d\n", 11 + 42);;
printf("%d\n", c);;
printf("%d\n", b);;
int32_t h = c;
printf("%d\n", 33);;
printf("%d\n", 43 * 13);;
printf("%d\n", f);;
printf("%d\n", 16);;
printf("%d\n", 54 * (d - 62));;
printf("%d\n", 46 - c);;
int32_t i = (((29 - d) * 26) - f) * (b + 45);
printf("%d\n", 31);;
int32_t j = i / (g * c);
printf("%d\n", b);;
printf("%d\n", 5 - 16);;
printf("%d\n", h);;
printf("%d\n", 67);;
printf("%d\n", 98);;
printf("%d\n", 13 - (d - (i / ((d * (d - (d * 28))) * c))));;
printf("%d\n", j);;
printf("%d\n", 12);;
printf("%d\n", (53 - (g + j)) - 83);;
printf("%d\n", ((d - 7) / 31) - a);;
printf("%d\n", 78 * b);;
printf("%d\n", 68);;
printf("%d\n", 9);;
printf("%d\n", 64);;
printf("%d\n", 30);;
int32_t k = 23;
printf("%d\n", e);;
int32_t l = k;
printf("%d\n", 5 * ((7 + 20) - a));;
printf("%d\n", 74);;
int32_t m = g;
int32_t n = (a + ((40 * g) / (10 - 58))) / 6;
printf("%d\n", a);;
int32_t o = 2 * (66 + (f + c));
printf("%d\n", 48);;
printf("%d\n", 75);;
printf("%d\n", m / k);;
printf("%d\n", i);;
printf("%d\n", i - (10 / 21));;
printf("%d\n", 32);;
int32_t p = 24;
int32_t q = h;
int32_t r = q;
printf("%d\n", d);;
int32_t s = 17;
printf("%d\n", k);;
printf("%d\n", (o + 15) - (q + s));;
printf("%d\n", e);;
int32_t t = 21;
int32_t u = (d / ((77 / d) - 23)) + k;
printf("%d\n", 48 / c);;
int32_t v = 85;
printf("%d\n", 15);;
printf("%d\n", q);;
printf("%d\n", 33);;
int32_t w = f;
printf("%d\n", i);;
int32_t x = 4;
int32_t y = u;
printf("%d\n", 3);;
printf("%d\n", y - (g / n));;
int32_t z = t;
int32_t aa = (89 / o) + 26;
printf("%d\n", n);;
printf("%d\n", a);;
int32_t ab = (((r + u) - 31) * ((n + (24 * j)) - 21)) + e;
int32_t ac = t;
printf("%d\n", 3 * ((38 / ((m - ((42 - 6) - 26)) + s)) + (12 * e)));;
printf("%d\n", (d - d) * ((z / (e * m)) * m));;
printf("%d\n", g);;
printf("%d\n", 48);;
printf("%d\n", 20);;
int32_t ad = (ac * (ab - 33)) - 67;
printf("%d\n", 19);;
printf("%d\n", y / 13);;
int32_t ae = 37 / (g / ab);
int32_t af = t;
printf("%d\n", 36);;
printf("%d\n", 14);;
int32_t ag = w;
printf("%d\n", h + 20);;
int32_t ah = 39;
printf("%d\n", ae / ad);;
int32_t ai = 9;
printf("%d\n", ad);;
printf("%d\n", 87);;
printf("%d\n", 7);;
int32_t aj = af;
printf("%d\n", 20);;
printf("%d\n", u);;
int32_t ak = d + 132;
printf("%d\n", aj);;
printf("%d\n", p);;
int32_t al = h;
printf("%d\n", 18);;
printf("%d\n", al);;
int32_t am = 7;
printf("%d\n", a);;
printf("%d\n", m);;
printf("%d\n", 5 + (t / s));;
printf("%d\n", 5);;
printf("%d\n", aa);;
int32_t an = l / x;
printf("%d\n", c);;
printf("%d\n", (v - 51) + 27);;
printf("%d\n", v);;
printf("%d\n", 3);;
printf("%d\n", 25 * (q - (77 * (m * 35))));;
printf("%d\n", 61);;
printf("%d\n", 77);;
printf("%d\n", s);;
printf("%d\n", 36);;
printf("%d\n", z * w);;
printf("%d\n", al);;
int32_t ao = f - g;
int32_t ap = (u / 30) * 46;
printf("%d\n", 7);;
int32_t aq = (aj + 26) + 5;
printf("%d\n", j);;
printf("%d\n", (26 / aq) - (p * 22));;
int32_t ar = 12;
printf("%d\n", v);;
int32_t as = 65 * (s * 28);
printf("%d\n", 25);;
printf("%d\n", 37);;
printf("%d\n", ((ap / (27 + ak)) * 90) * 18);;
printf("%d\n", n / (ae * 33));;
printf("%d\n", ((45 - w) * u) + (v / 58));;
int32_t at = ar * af;
printf("%d\n", 38);;
printf("%d\n", 7);;
printf("%d\n", 36 - c);;
int32_t au = 71;
printf("%d\n", 44 - 6);;
int32_t av = i;
printf("%d\n", 52);;
int32_t aw = 32 - (24 / (y + 34));
printf("%d\n", n);;
printf("%d\n", 45);;
printf("%d\n", 2);;
printf("%d\n", ao);;
printf("%d\n", g);;
printf("%d\n", 108);;
int32_t ax = ao;
printf("%d\n", 66 + q);;
printf("%d\n", h);;
int32_t ay = 5 / 1;
printf("%d\n", x);;
printf("%d\n", aq);;
printf("%d\n", 22);;
printf("%d\n", 52);;
printf("%d\n", ((ah + (((56 / (63 + (d * ((((ab * (x * (41 + (ab + l)))) - ag) / 11) * 9)))) / at) + (((an * 7) / 40) - (al / 59)))) * ar) - ((54 + 44) - 60));;
printf("%d\n", 17 - ((ac * 10) + 17));;
int32_t az = 10 * ab;
int32_t bb = 14;
int32_t bc = 47;
printf("%d\n", 1);;
printf("%d\n", 40);;
printf("%d\n", 23);;
printf("%d\n", 33);;
printf("%d\n", 25);;
printf("%d\n", ah * c);;
printf("%d\n", 6);;
int32_t bd = af;
printf("%d\n", ax);;
printf("%d\n", as);;
printf("%d\n", 20 * g);;
printf("%d\n", 7 * ab);;
printf("%d\n", ((((((bc + af) + 95) - 35) / 20) * x) + 45) / 5);;
printf("%d\n", ((s * 5) * (o + (ac + ae))) / n);;
int32_t be = z;
printf("%d\n", m * l);;
printf("%d\n", 4);;
printf("%d\n", 1);;
printf("%d\n", 18 - 28);;
printf("%d\n", av);;
printf("%d\n", ai);;
printf("%d\n", f);;
printf("%d\n", j);;
int32_t bf = ab;
printf("%d\n", z);;
printf("%d\n", au);;
int32_t bg = ag * bf;
printf("%d\n", 29);;
printf("%d\n", c / 61);;
printf("%d\n", 34);;
printf("%d\n", 9 + (az / 19));;
printf("%d\n", 55);;
printf("%d\n", at);;
printf("%d\n", 41);;
printf("%d\n", 20 - ax);;
printf("%d\n", 37 + ad);;
int32_t bh = 44;
int32_t bi = 4;
return 0;}