#include <stdio.h>
#include <stdint.h>
int main() {
int32_t a = 13;
int32_t b = a * (a / ((12 + a) - 1));
printf("%d\n", 8);;
printf("%d\n", a);;
printf("%d\n", 9 / a);;
int32_t c = 26;
printf("%d\n", a - b);;
printf("%d\n", b);;
int32_t d = 1;
int32_t e = (1 + 23) / 10;
int32_t f = 17;
printf("%d\n", 10);;
printf("%d\n", a);;
printf("%d\n", d);;
printf("%d\n", 5);;
printf("%d\n", 59);;
printf("%d\n", b * f);;
printf("%d\n", d);;
printf("%d\n", 33);;
printf("%d\n", 14);;
printf("%d\n", 15);;
int32_t g = ((10 - ((a * c) - 52)) - (32 - 7)) * f;
printf("%d\n", 59);;
printf("%d\n", 53);;
printf("%d\n", 15);;
printf("%d\n", 6 - e);;
printf("%d\n", g);;
printf("%d\n", a - ((f - d) * 19));;
int32_t h = 29;
int32_t i = f + 15;
printf("%d\n", 30);;
int32_t j = c;
printf("%d\n", 93);;
printf("%d\n", 80 + 46);;
printf("%d\n", 18);;
printf("%d\n", a + 5);;
int32_t k = 1;
int32_t l = j;
printf("%d\n", 4);;
printf("%d\n", g);;
printf("%d\n", 40);;
int32_t m = c;
printf("%d\n", 45);;
printf("%d\n", 5);;
printf("%d\n", 32 * (34 - m));;
int32_t n = h;
int32_t o = (((j / c) * m) + (((m / j) * 26) - j)) + 52;
printf("%d\n", (m * 3) - e);;
printf("%d\n", a);;
int32_t p = 23;
printf("%d\n", l);;
printf("%d\n", 47 - 8);;
printf("%d\n", 22);;
printf("%d\n", 20);;
printf("%d\n", a);;
int32_t q = f;
printf("%d\n", ((((a * (51 * l)) - (p * 46)) - 31) / (14 - d)) - i);;
int32_t r = a;
printf("%d\n", (((g + 87) * d) + ((j - 35) / (o / p))) * k);;
printf("%d\n", n);;
printf("%d\n", l - 2);;
printf("%d\n", 21);;
printf("%d\n", n * 27);;
printf("%d\n", 46);;
printf("%d\n", e);;
printf("%d\n", m);;
printf("%d\n", n);;
printf("%d\n", c / (((h / ((2 - 4) * 8)) + d) + 62));;
printf("%d\n", 17 + (7 + (54 * (36 + (14 - ((4 / 17) * g))))));;
int32_t s = 5;
printf("%d\n", o);;
int32_t t = 42;
printf("%d\n", 83);;
printf("%d\n", (c - ((22 - 4) * 10)) / f);;
printf("%d\n", d);;
printf("%d\n", o - g);;
printf("%d\n", j - c);;
int32_t u = 25 + h;
int32_t v = f;
printf("%d\n", c);;
int32_t w = 13;
printf("%d\n", 36);;
printf("%d\n", p);;
printf("%d\n", 8);;
int32_t x = 14;
int32_t y = 32;
int32_t z = 7;
printf("%d\n", 38);;
printf("%d\n", 45 * 4);;
printf("%d\n", b);;
printf("%d\n", v);;
printf("%d\n", f + 6);;
printf("%d\n", 34 + (2 - k));;
printf("%d\n", (q - 30) - u);;
int32_t aa = u;
printf("%d\n", 75);;
printf("%d\n", 21 - (x * p));;
int32_t ab = 3;
int32_t ac = 7;
printf("%d\n", y);;
int32_t ad = r / (9 + ab);
printf("%d\n", 79 * c);;
int32_t ae = a;
printf("%d\n", 42);;
printf("%d\n", 7);;
int32_t af = s;
printf("%d\n", 62);;
printf("%d\n", h);;
printf("%d\n", af);;
printf("%d\n", 67);;
printf("%d\n", 18);;
printf("%d\n", f);;
printf("%d\n", (5 / 27) - 16);;
printf("%d\n", (4 * (60 - k)) + 23);;
printf("%d\n", 33);;
printf("%d\n", 55);;
printf("%d\n", w);;
int32_t ag = 2;
printf("%d\n", ((((8 * ((69 / 40) + (46 / 6))) - d) * ae) * ((g - 31) * (33 + n))) + s);;
int32_t ah = m;
printf("%d\n", (i + 58) - (d - (c + 48)));;
int32_t ai = k;
int32_t aj = 60;
printf("%d\n", b);;
printf("%d\n", r);;
printf("%d\n", 74);;
printf("%d\n", (v - 59) + (70 / ab));;
printf("%d\n", 18);;
printf("%d\n", 101 + ah);;
printf("%d\n", 40 / 43);;
printf("%d\n", 2);;
printf("%d\n", (3 + v) + w);;
int32_t ak = ab - 28;
printf("%d\n", 18);;
printf("%d\n", 12 * k);;
int32_t al = 18;
printf("%d\n", g - aa);;
printf("%d\n", ah);;
printf("%d\n", (49 / (v + z)) + i);;
int32_t am = 36;
int32_t an = q + (21 - ((4 + p) - (ae / 49)));
int32_t ao = p;
printf("%d\n", 52);;
printf("%d\n", ao);;
printf("%d\n", 7 + ae);;
int32_t ap = 17 - 12;
int32_t aq = 21;
printf("%d\n", b);;
printf("%d\n", z);;
printf("%d\n", 8);;
printf("%d\n", 46);;
printf("%d\n", m);;
printf("%d\n", 22 - ac);;
printf("%d\n", 72);;
printf("%d\n", 16 / 8);;
int32_t ar = ap;
printf("%d\n", ae);;
printf("%d\n", 42);;
printf("%d\n", x + ae);;
printf("%d\n", 10);;
printf("%d\n", 6);;
printf("%d\n", x);;
printf("%d\n", 16);;
int32_t as = 30;
printf("%d\n", m);;
int32_t at = 125;
int32_t au = u;
int32_t av = am;
int32_t aw = 16 * 70;
int32_t ax = 65;
printf("%d\n", 31);;
int32_t ay = 43;
int32_t az = 3 / 1;
printf("%d\n", 4);;
printf("%d\n", 3);;
int32_t bb = 11;
printf("%d\n", 29);;
printf("%d\n", ab);;
printf("%d\n", (48 - 93) + 3);;
printf("%d\n", an);;
int32_t bc = au;
printf("%d\n", m);;
printf("%d\n", ay);;
printf("%d\n", 5);;
printf("%d\n", 10 * (44 / 74));;
printf("%d\n", 65);;
printf("%d\n", 11);;
printf("%d\n", 51);;
printf("%d\n", 87);;
printf("%d\n", ah * x);;
printf("%d\n", ai);;
int32_t bd = ad - 61;
printf("%d\n", n / (o - ac));;
printf("%d\n", e / ai);;
printf("%d\n", 39);;
printf("%d\n", 18);;
printf("%d\n", 14);;
printf("%d\n", (ag + aw) + 64);;
int32_t be = 10 - (44 + 3);
printf("%d\n", 54);;
printf("%d\n", 30);;
int32_t bf = aj;
printf("%d\n", n);;
printf("%d\n", v);;
int32_t bg = 69;
printf("%d\n", ag);;
printf("%d\n", bg);;
printf("%d\n", ab);;
int32_t bh = 75 * 27;
printf("%d\n", ay);;
printf("%d\n", 1 / af);;
printf("%d\n", 36);;
printf("%d\n", j);;
printf("%d\n", 90 * 17);;
printf("%d\n", 100);;
printf("%d\n", ((az + 8) - (53 + (at + w))) + (ax * bf));;
printf("%d\n", 39);;
printf("%d\n", av);;
printf("%d\n", 8);;
printf("%d\n", (11 / (11 + ad)) - e);;
printf("%d\n", (7 - ak) + ab);;
printf("%d\n", m);;
printf("%d\n", aq);;
printf("%d\n", af);;
printf("%d\n", ao);;
printf("%d\n", 7);;
printf("%d\n", bg);;
printf("%d\n", ((af - (52 + an)) + 30) * ag);;
int32_t bi = be * (((4 - af) * p) / (a / ((az + (11 / q)) / k)));
printf("%d\n", (39 - 8) - o);;
printf("%d\n", 59);;
printf("%d\n", 18);;
printf("%d\n", bi);;
printf("%d\n", 11 / (1 - 8));;
printf("%d\n", 10);;
printf("%d\n", 21);;
printf("%d\n", be);;
printf("%d\n", d * aj);;
printf("%d\n", (d * ag) - ((16 + (((58 / 41) / 92) + w)) + (5 + (((q - ap) + ((aa / (c * (34 * (3 - ae)))) - as)) + 37))));;
printf("%d\n", bi);;
printf("%d\n", bh);;
printf("%d\n", m);;
printf("%d\n", 35);;
printf("%d\n", q);;
printf("%d\n", 21);;
printf("%d\n", 111 * g);;
int32_t bj = 12;
printf("%d\n", (m * j) + (29 + af));;
printf("%d\n", 58 - ah);;
printf("%d\n", 80 * x);;
printf("%d\n", 50);;
printf("%d\n", d / (at + bi));;
printf("%d\n", 28);;
printf("%d\n", 11);;
printf("%d\n", 15);;
int32_t bk = l;
printf("%d\n", ((16 - au) / n) + 2);;
int32_t bl = z * m;
printf("%d\n", 22);;
int32_t bm = 31;
int32_t bn = 66;
printf("%d\n", ((az - o) * (ae * (30 - aw))) / 26);;
printf("%d\n", 34);;
return 0;}