#!/bin/bash

filePath=$1

fileDir=$(dirname "${filePath}")

fileNameExt=$(basename "${filePath}")

fileName="${fileNameExt%.*}"

build/Compiler JVM $fileName < $filePath

cp output/out.j $fileDir/$fileName.j

java -jar jasmin/jasmin.jar $fileDir/$fileName.j -d $fileDir
