#!/bin/bash

filePath=$1

fileDir=$(dirname "${filePath}")

fileNameExt=$(basename "${filePath}")

fileName="${fileNameExt%.*}"

build/Compiler JVM $fileDir $fileName < $filePath

jFile = $fileDir/$fileName.j

java -jar jasmin/jasmin.jar $jFile -d $fileDir
