#include <stdio.h>
#include <stdint.h>
int main() {
int32_t a = 49;
printf("%d\n", 60);;
printf("%d\n", a / a);;
printf("%d\n", 47 + 3);;
printf("%d\n", ((a * 15) + 5) + (a * 30));;
printf("%d\n", 104);;
int32_t b = a;
printf("%d\n", b);;
printf("%d\n", 21 - 20);;
printf("%d\n", a);;
printf("%d\n", 37 + (((34 - a) - (21 - 45)) * (10 + b)));;
int32_t c = a;
printf("%d\n", 24 + ((40 * a) + 1));;
printf("%d\n", 14);;
int32_t d = a * 9;
printf("%d\n", b);;
int32_t e = (d * 44) / b;
printf("%d\n", 49 * e);;
printf("%d\n", 47);;
printf("%d\n", 42);;
int32_t f = 29;
printf("%d\n", f);;
printf("%d\n", b);;
printf("%d\n", 7);;
printf("%d\n", 28 - (((d * (79 / 29)) + (53 * 3)) + e));;
int32_t g = 115;
printf("%d\n", f / 15);;
int32_t h = f * 30;
int32_t i = 15;
printf("%d\n", 40);;
int32_t j = 24;
printf("%d\n", 30 + 26);;
printf("%d\n", f);;
printf("%d\n", 2);;
int32_t k = b;
printf("%d\n", 25 - ((17 + d) / 18));;
printf("%d\n", h);;
printf("%d\n", 18);;
printf("%d\n", 42 / h);;
printf("%d\n", d);;
int32_t l = 38;
int32_t m = b;
printf("%d\n", 20);;
printf("%d\n", i + g);;
printf("%d\n", g);;
printf("%d\n", e * (37 / 39));;
printf("%d\n", m);;
printf("%d\n", 64);;
int32_t n = g;
int32_t o = g;
printf("%d\n", l * (o / i));;
printf("%d\n", 27);;
printf("%d\n", b);;
int32_t p = 5;
printf("%d\n", d);;
int32_t q = g;
printf("%d\n", 14);;
printf("%d\n", 10 * ((d - (k - e)) - e));;
printf("%d\n", o);;
int32_t r = q;
printf("%d\n", 14);;
printf("%d\n", l);;
printf("%d\n", c);;
printf("%d\n", 48);;
int32_t s = k;
int32_t t = 66;
printf("%d\n", g);;
printf("%d\n", g);;
printf("%d\n", t);;
printf("%d\n", q);;
printf("%d\n", i);;
int32_t u = 8 + c;
printf("%d\n", l);;
printf("%d\n", (j / m) * 10);;
printf("%d\n", 66);;
printf("%d\n", o);;
printf("%d\n", i);;
printf("%d\n", 24);;
int32_t v = 25;
printf("%d\n", 66);;
int32_t w = 56;
int32_t x = n + b;
printf("%d\n", u);;
printf("%d\n", q);;
printf("%d\n", s);;
int32_t y = d / h;
printf("%d\n", l);;
int32_t z = p;
int32_t aa = o * ((e * ((b + 7) * 9)) / 33);
int32_t ab = 60;
printf("%d\n", s);;
int32_t ac = 21;
printf("%d\n", 25);;
printf("%d\n", f / (a - (a * h)));;
printf("%d\n", f);;
int32_t ad = z;
int32_t ae = p;
printf("%d\n", 51);;
printf("%d\n", (a - ((45 / (((23 + 69) / 12) + 34)) / t)) - d);;
int32_t af = f;
int32_t ag = q;
printf("%d\n", 49);;
printf("%d\n", f);;
printf("%d\n", f * 64);;
printf("%d\n", 91);;
int32_t ah = (49 * 18) / 44;
printf("%d\n", 50 * ((5 / x) + b));;
printf("%d\n", u);;
printf("%d\n", n - (3 - (17 * (s - 13))));;
printf("%d\n", 37 - 3);;
int32_t ai = 21;
printf("%d\n", b - l);;
printf("%d\n", (51 + (44 + 43)) - (19 + (z / 54)));;
printf("%d\n", (20 * (2 * (6 / (ai * (u * g))))) * m);;
printf("%d\n", 31 / j);;
int32_t aj = w * 5;
int32_t ak = 82;
printf("%d\n", 15);;
int32_t al = l;
int32_t am = c;
printf("%d\n", 26 / (17 * (5 * (66 * t))));;
printf("%d\n", 6);;
int32_t an = 46;
int32_t ao = ab / 78;
int32_t ap = 19;
printf("%d\n", 82);;
printf("%d\n", a);;
printf("%d\n", 50);;
printf("%d\n", 19);;
printf("%d\n", ab);;
printf("%d\n", k);;
printf("%d\n", 61);;
printf("%d\n", v);;
printf("%d\n", 17);;
printf("%d\n", al / u);;
printf("%d\n", 7 / ab);;
int32_t aq = z;
printf("%d\n", 18);;
printf("%d\n", f);;
int32_t ar = r / (45 * 8);
printf("%d\n", 11);;
printf("%d\n", 18);;
printf("%d\n", 100);;
printf("%d\n", 38);;
int32_t as = (o / aq) - s;
int32_t at = i;
int32_t au = i;
printf("%d\n", 102);;
int32_t av = at;
printf("%d\n", 47);;
printf("%d\n", j / ak);;
printf("%d\n", ag);;
printf("%d\n", 23 - ah);;
printf("%d\n", u * s);;
printf("%d\n", t);;
printf("%d\n", j);;
int32_t aw = 22;
printf("%d\n", w);;
printf("%d\n", ((6 / 5) * 38) + 50);;
printf("%d\n", 35 * (9 * (ai + b)));;
printf("%d\n", 21);;
printf("%d\n", 2);;
printf("%d\n", 59);;
int32_t ax = ag;
printf("%d\n", z - ac);;
printf("%d\n", 5);;
int32_t ay = 15 + ((n / e) / ae);
printf("%d\n", s);;
printf("%d\n", (12 * (39 / (77 - (36 / u)))) / (19 * 14));;
printf("%d\n", 12);;
printf("%d\n", i);;
printf("%d\n", aq - ((56 + 4) - (aj - p)));;
printf("%d\n", w);;
printf("%d\n", ai);;
printf("%d\n", au);;
printf("%d\n", 74);;
printf("%d\n", ap / z);;
printf("%d\n", r);;
int32_t az = al;
printf("%d\n", ((34 / j) - 33) / 90);;
printf("%d\n", 15);;
printf("%d\n", 31 + ao);;
printf("%d\n", j);;
int32_t bb = d;
printf("%d\n", ar);;
printf("%d\n", 81);;
printf("%d\n", 47);;
int32_t bc = (24 / (20 + 2)) * n;
printf("%d\n", u);;
printf("%d\n", (21 - 0) - ao);;
printf("%d\n", az);;
int32_t bd = ay;
int32_t be = p;
printf("%d\n", 12 * az);;
int32_t bf = an;
printf("%d\n", (j / h) / o);;
int32_t bg = 58;
printf("%d\n", 8);;
int32_t bh = 1;
printf("%d\n", y);;
printf("%d\n", 35);;
printf("%d\n", 20);;
printf("%d\n", (s * ((aa - (c * 3)) / 40)) * 82);;
printf("%d\n", 7);;
printf("%d\n", e);;
printf("%d\n", 49);;
int32_t bi = ac;
int32_t bj = w / am;
printf("%d\n", 100);;
printf("%d\n", as);;
printf("%d\n", 2);;
printf("%d\n", s);;
int32_t bk = az / 14;
printf("%d\n", 74 - (72 - ay));;
printf("%d\n", f);;
printf("%d\n", ((aa / ay) / bd) / (av / 11));;
int32_t bl = 35 - 12;
printf("%d\n", (25 * (74 - 16)) / ((w * at) - 43));;
printf("%d\n", a + ((3 - v) + 58));;
printf("%d\n", 45);;
int32_t bm = bf / (ac - (j + (c / 22)));
int32_t bn = 51;
int32_t bo = 52;
printf("%d\n", ag);;
printf("%d\n", 6 + (l * ((k * i) + 10)));;
printf("%d\n", 2);;
int32_t bp = 44;
printf("%d\n", 22);;
printf("%d\n", 106);;
printf("%d\n", be / f);;
printf("%d\n", as / bo);;
printf("%d\n", 56);;
printf("%d\n", bp - 65);;
int32_t bq = l;
printf("%d\n", bm - (az - 28));;
int32_t br = ((38 / (23 * 17)) * 19) - (0 - s);
return 0;}