#include <stdio.h>
#include <stdint.h>
int main() {
printf("%d\n", 5 - 11);;
int32_t a = 89;
printf("%d\n", a / a);;
printf("%d\n", a);;
printf("%d\n", 10);;
printf("%d\n", a - (a - (3 * (a * 8))));;
printf("%d\n", a);;
printf("%d\n", 2);;
printf("%d\n", a);;
int32_t b = (((((a * a) / ((27 * 0) + 100)) - a) + (a * 14)) + a) * 52;
int32_t c = 69;
printf("%d\n", 100);;
printf("%d\n", 93);;
printf("%d\n", 11);;
printf("%d\n", 26);;
printf("%d\n", 29);;
printf("%d\n", c);;
printf("%d\n", a);;
printf("%d\n", b + (b / (4 + 66)));;
printf("%d\n", b);;
printf("%d\n", 8);;
printf("%d\n", 19 - c);;
printf("%d\n", 15 - 14);;
int32_t d = ((44 + (b - (10 - b))) * 40) / 50;
printf("%d\n", 9);;
printf("%d\n", a / 58);;
int32_t e = 0;
int32_t f = c - d;
printf("%d\n", (b + a) + (26 / (23 * b)));;
printf("%d\n", 30 / 11);;
printf("%d\n", (c * a) + e);;
int32_t g = d;
printf("%d\n", 25);;
int32_t h = 17;
int32_t i = 39;
int32_t j = a;
printf("%d\n", d);;
printf("%d\n", i);;
printf("%d\n", c);;
printf("%d\n", i);;
int32_t k = 41;
printf("%d\n", (46 * h) / 57);;
printf("%d\n", 7);;
int32_t l = 22 - 106;
printf("%d\n", j / 25);;
int32_t m = g;
printf("%d\n", 2);;
printf("%d\n", g);;
int32_t n = ((((13 * k) + j) + 70) * 76) * b;
printf("%d\n", 4);;
printf("%d\n", 46);;
printf("%d\n", 4 + 54);;
printf("%d\n", e);;
printf("%d\n", n);;
printf("%d\n", 1);;
int32_t o = 27;
printf("%d\n", 1);;
int32_t p = 1;
int32_t q = m;
printf("%d\n", d * (30 * (50 * (47 * k))));;
int32_t r = 61 + (n - 1);
printf("%d\n", d - 24);;
printf("%d\n", q);;
printf("%d\n", (j * 10) + 25);;
printf("%d\n", e + 22);;
printf("%d\n", j);;
int32_t s = 5 / c;
printf("%d\n", (k - (31 + 7)) - n);;
printf("%d\n", n);;
int32_t t = j;
printf("%d\n", 30);;
printf("%d\n", 26 / o);;
printf("%d\n", 37);;
printf("%d\n", 11);;
int32_t u = h;
printf("%d\n", p);;
printf("%d\n", u);;
printf("%d\n", 92);;
printf("%d\n", 56 - d);;
printf("%d\n", 33);;
printf("%d\n", 71 * 48);;
int32_t v = 68;
printf("%d\n", v);;
printf("%d\n", (28 - 47) - l);;
printf("%d\n", 5);;
printf("%d\n", 30 + l);;
int32_t w = n;
printf("%d\n", u);;
printf("%d\n", s + (a * i));;
int32_t x = m;
printf("%d\n", 38);;
printf("%d\n", 28);;
printf("%d\n", g);;
printf("%d\n", k);;
printf("%d\n", l);;
printf("%d\n", 42);;
int32_t y = 26 / a;
printf("%d\n", y * (w / (41 + 14)));;
printf("%d\n", j);;
printf("%d\n", a);;
printf("%d\n", j + n);;
printf("%d\n", 7);;
printf("%d\n", u);;
printf("%d\n", 36);;
printf("%d\n", p * (34 * (a - 27)));;
int32_t z = b;
int32_t aa = l;
printf("%d\n", 14);;
int32_t ab = 4;
int32_t ac = 13;
printf("%d\n", ((48 / u) - 33) + q);;
printf("%d\n", s);;
printf("%d\n", q + 19);;
printf("%d\n", k);;
printf("%d\n", ac);;
int32_t ad = 32;
int32_t ae = i;
int32_t af = i;
int32_t ag = u;
printf("%d\n", ((33 + m) + y) / (i - 2));;
printf("%d\n", 40);;
int32_t ah = 12;
printf("%d\n", 9);;
printf("%d\n", (r * 34) * ((g + ad) + ah));;
int32_t ai = u;
printf("%d\n", ag);;
printf("%d\n", 6);;
int32_t aj = 69;
printf("%d\n", i + (34 + (m + (w * ae))));;
printf("%d\n", w);;
int32_t ak = 27;
int32_t al = ai;
printf("%d\n", ah);;
printf("%d\n", ((l / ab) + (ad - (70 * 1))) * 52);;
printf("%d\n", h);;
int32_t am = 30;
printf("%d\n", n + 19);;
printf("%d\n", ((q + (p - am)) + x) * al);;
printf("%d\n", 64);;
printf("%d\n", 26);;
printf("%d\n", ab);;
printf("%d\n", 82);;
int32_t an = 40;
printf("%d\n", al);;
printf("%d\n", n);;
printf("%d\n", 2);;
printf("%d\n", q);;
printf("%d\n", 22 * 34);;
int32_t ao = i;
printf("%d\n", aa);;
printf("%d\n", ad);;
printf("%d\n", 44);;
printf("%d\n", ((((1 / 14) - d) * i) + ((21 * (r - ((ak - 68) - ((j / (h - 7)) - c)))) / 109)) * ((((ao / (((m * an) / (67 - b)) - (((s / q) * ((94 / ae) * ao)) * w))) + 3) + 19) / ((((u * d) / u) * (i - (l * 23))) + ((w * (50 / (64 - 8))) * 11))));;
printf("%d\n", 13);;
printf("%d\n", 102);;
printf("%d\n", b);;
printf("%d\n", 3);;
printf("%d\n", 48 + 1);;
printf("%d\n", 70);;
printf("%d\n", ai * (ae - 59));;
printf("%d\n", 63);;
printf("%d\n", b);;
printf("%d\n", 68);;
printf("%d\n", w);;
printf("%d\n", r);;
printf("%d\n", 7);;
printf("%d\n", 52 / (d / g));;
printf("%d\n", f - 17);;
int32_t ap = 132;
int32_t aq = 64;
printf("%d\n", ac + ac);;
int32_t ar = 37;
printf("%d\n", 59);;
int32_t as = d * 39;
printf("%d\n", 28);;
int32_t at = am;
printf("%d\n", aj);;
int32_t au = ah;
printf("%d\n", a);;
printf("%d\n", ai);;
printf("%d\n", an / ((64 * (26 * (at + (c * au)))) * 7));;
printf("%d\n", 95);;
printf("%d\n", ah + k);;
return 0;}