#include <stdio.h>
#include <stdint.h>
int main() {
printf("%d\n", (15 + (((1 * 17) + 42) / 59)) / 15);;
printf("%d\n", 35);;
printf("%d\n", 21);;
printf("%d\n", 97);;
int32_t a = 22 + 23;
int32_t b = 68;
int32_t c = 10;
int32_t d = a;
printf("%d\n", 15 * c);;
printf("%d\n", 10);;
int32_t e = 24;
int32_t f = b + d;
printf("%d\n", c);;
printf("%d\n", 47 / ((10 * (7 - d)) * (12 + b)));;
printf("%d\n", 32);;
printf("%d\n", a);;
int32_t g = d;
printf("%d\n", 20);;
printf("%d\n", f);;
printf("%d\n", 10);;
printf("%d\n", 8 + e);;
int32_t h = b;
int32_t i = 5 + 49;
int32_t j = i;
int32_t k = 12;
printf("%d\n", (((h - 14) + 8) + 33) - j);;
printf("%d\n", (15 * (29 + 4)) - h);;
printf("%d\n", i);;
printf("%d\n", f);;
printf("%d\n", 58 + (51 + e));;
printf("%d\n", (15 - (i + 62)) / 57);;
printf("%d\n", i);;
printf("%d\n", j);;
printf("%d\n", 11 - j);;
int32_t l = d;
int32_t m = c;
int32_t n = 5;
printf("%d\n", (11 - (75 + (j - e))) * n);;
printf("%d\n", 10);;
printf("%d\n", 15);;
printf("%d\n", (c + 32) / i);;
int32_t o = (((((((38 + n) * (g + l)) - (5 / 24)) / 33) - b) * 61) + 8) * 8;
printf("%d\n", ((m * g) * e) - 0);;
printf("%d\n", 15 * (39 / 19));;
printf("%d\n", 22);;
int32_t p = h;
printf("%d\n", 1);;
printf("%d\n", i * ((18 - b) * (n * b)));;
printf("%d\n", 51 * (11 - (p / 29)));;
printf("%d\n", k * 69);;
int32_t q = (i * (p * 6)) - e;
int32_t r = 14;
printf("%d\n", 56);;
int32_t s = d - (f + p);
int32_t t = (q - 16) / 32;
printf("%d\n", o);;
printf("%d\n", 22);;
int32_t u = a;
printf("%d\n", 8);;
int32_t v = d - 39;
printf("%d\n", 25);;
printf("%d\n", s);;
printf("%d\n", e);;
printf("%d\n", a);;
printf("%d\n", v);;
printf("%d\n", g);;
printf("%d\n", 16 * (66 * 27));;
printf("%d\n", k);;
int32_t w = 22 + 9;
printf("%d\n", w / ((u + 24) - 14));;
printf("%d\n", 33);;
printf("%d\n", 40);;
int32_t x = 7 / ((e - 18) * 4);
printf("%d\n", i);;
printf("%d\n", 40);;
int32_t y = 13 + 15;
printf("%d\n", 21);;
printf("%d\n", a);;
printf("%d\n", 64 * (8 - (47 + s)));;
printf("%d\n", x - c);;
printf("%d\n", 19);;
int32_t z = ((h - i) + (((114 / (39 * (5 + (y - (a * (c + 35)))))) * 38) - q)) + 5;
int32_t aa = 44;
printf("%d\n", aa);;
int32_t ab = 60;
int32_t ac = 41;
printf("%d\n", ab);;
printf("%d\n", 41);;
printf("%d\n", 3);;
printf("%d\n", b - (81 / 41));;
printf("%d\n", 42);;
printf("%d\n", 41);;
int32_t ad = x;
printf("%d\n", ac * p);;
int32_t ae = m;
printf("%d\n", 1);;
int32_t af = 22;
int32_t ag = 16;
printf("%d\n", f / (13 * d));;
printf("%d\n", g);;
printf("%d\n", n);;
printf("%d\n", 1 / ab);;
printf("%d\n", 8);;
printf("%d\n", y);;
printf("%d\n", g);;
printf("%d\n", 32);;
printf("%d\n", (11 - t) + x);;
printf("%d\n", u);;
printf("%d\n", w / w);;
printf("%d\n", p);;
printf("%d\n", 12);;
printf("%d\n", 29);;
printf("%d\n", r);;
int32_t ah = 48 / 6;
int32_t ai = 41 - 50;
int32_t aj = j;
printf("%d\n", j);;
printf("%d\n", k);;
printf("%d\n", q * af);;
printf("%d\n", ah - 4);;
printf("%d\n", (c + (39 - 71)) - 7);;
printf("%d\n", 58);;
printf("%d\n", 18);;
int32_t ak = h;
printf("%d\n", (37 / r) / 102);;
printf("%d\n", 8);;
int32_t al = 13 - 21;
printf("%d\n", 71);;
int32_t am = 62 / 45;
printf("%d\n", t);;
printf("%d\n", k);;
printf("%d\n", a);;
printf("%d\n", d);;
int32_t an = x;
printf("%d\n", 29);;
printf("%d\n", 37);;
printf("%d\n", aj / ((u + u) * 12));;
printf("%d\n", n);;
printf("%d\n", 71);;
printf("%d\n", al / n);;
int32_t ao = a;
printf("%d\n", l);;
int32_t ap = 31 * c;
int32_t aq = h;
printf("%d\n", c);;
return 0;}