#include <stdio.h>
#include <stdint.h>
int main() {
printf("%d\n", 3);;
printf("%d\n", (23 + 40) * (30 + (35 * 17)));;
printf("%d\n", 9);;
printf("%d\n", 18);;
printf("%d\n", 31);;
int32_t a = 33 + (18 + (49 - 23));
printf("%d\n", 47);;
int32_t b = a;
printf("%d\n", 34);;
printf("%d\n", ((24 * (12 * (b - 16))) - b) / ((a * ((4 - (a + a)) / a)) + (34 + 39)));;
int32_t c = 14 - (b - ((a * 37) * 4));
printf("%d\n", (((38 * (a - a)) * b) - c) * c);;
printf("%d\n", 48);;
printf("%d\n", 23 * ((((a + b) / c) / 48) * b));;
printf("%d\n", a);;
int32_t d = a;
printf("%d\n", 12);;
printf("%d\n", d - 37);;
printf("%d\n", d);;
printf("%d\n", 54);;
printf("%d\n", 4 / d);;
int32_t e = d;
printf("%d\n", e);;
printf("%d\n", 8);;
printf("%d\n", ((((32 * 16) - 52) - b) - (45 + (((18 + (c - 20)) - b) / 9))) - a);;
printf("%d\n", e);;
printf("%d\n", 50 + (b - b));;
printf("%d\n", 43);;
printf("%d\n", ((5 - d) * 8) / 14);;
printf("%d\n", b - 41);;
int32_t f = c;
printf("%d\n", b);;
printf("%d\n", a / d);;
printf("%d\n", 6);;
printf("%d\n", f);;
printf("%d\n", d);;
printf("%d\n", c);;
printf("%d\n", d);;
printf("%d\n", 76);;
printf("%d\n", (47 - e) / (b - (((((4 - 79) + 63) * f) * (d * ((98 + ((a - d) - (f * 9))) / 14))) - (35 / a))));;
printf("%d\n", 5);;
int32_t g = 39;
printf("%d\n", 32 + (53 * (c / (e * (12 + (d / (39 - a)))))));;
printf("%d\n", g);;
printf("%d\n", (f / 74) + ((((g * (35 * (2 - 2))) / 23) + (((d - e) - (c - 23)) * (11 - 3))) / 8));;
printf("%d\n", 58);;
printf("%d\n", 15 * (a + a));;
printf("%d\n", 0);;
printf("%d\n", e);;
printf("%d\n", ((((c / b) / c) * a) * c) - 11);;
printf("%d\n", 14 - (6 + 30));;
printf("%d\n", 85);;
printf("%d\n", c - f);;
printf("%d\n", f);;
int32_t h = f;
printf("%d\n", (e * c) - f);;
printf("%d\n", 68 * h);;
int32_t i = 69;
printf("%d\n", 31);;
printf("%d\n", (f + (d / (h / 19))) * a);;
printf("%d\n", f);;
printf("%d\n", c);;
printf("%d\n", h);;
printf("%d\n", f);;
printf("%d\n", ((c * 83) / 36) + 57);;
printf("%d\n", 67);;
printf("%d\n", 74);;
printf("%d\n", i / 3);;
printf("%d\n", h);;
printf("%d\n", c);;
return 0;}