#!/bin/bash

filePath=$1

fileDir=$(dirname "${filePath}")

if [ -z "$fileDir" ]; then
    
    fileDir = "."

fi

fileNameExt=$(basename "${filePath}")

fileName="${fileNameExt%.*}"

build/Compiler JVM $fileDir $fileName < $filePath

jFile=$fileDir/$fileName.j

if [ -f $jFile ]; then
   
    java -jar jasmin/jasmin.jar $jFile -d $fileDir

fi
